# -*- coding: utf-8 -*-
import sys, io
sys.path.insert(0, r"C:/Users/14053/hermes-projects/badlands-substack/scripts")
from _merge243 import merge

merge("entities/tom-barrack.md", u"""## Damascus flag-raising and the Syria portfolio (May 2025)

On Thursday, May 29, 2025, the American flag was raised outside the long-dormant U.S. ambassador's residence in Damascus, the first time it had flown there since 2012, signaling a significant shift in relations between Washington and Syria's new leadership.[n] Tom Barrack — U.S. ambassador to [[turkey|Turkey]] and newly appointed special envoy to [[syria|Syria]] — arrived in Damascus for the symbolic ceremony.[n] Speaking to Al Arabiya, Barrack called the decades-old Syrian-Israeli conflict a "solvable problem" and floated the idea of a "non-aggression agreement" as a step toward regional stability.[n]

The thaw coincided with Reuters reports that Israel and Syria had been engaged in direct talks, including recent in-person meetings, to reduce tensions along their border.[n] Although the United States had not formally reopened its embassy, the [[trump-administration|Trump administration]] — backed by regional allies [[saudi-arabia|Saudi Arabia]] and Turkey — had grown increasingly open to engaging Damascus, with President [[donald-trump|Trump]] having met Syrian President [[ahmed-al-sharaa|Ahmad al-Sharaa]] earlier that month in Riyadh and the U.S. beginning to scale back longstanding sanctions.[n]

During the visit Barrack met al-Sharaa and attended the signing of an agreement for a consortium of Qatari, Turkish, and U.S. companies to develop a 5,000-megawatt energy project intended to revitalize much of Syria's war-battered electricity grid.[n]

## Badlands assessment of Barrack's network

Badlands contributor [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] characterized Barrack as a longtime friend and supporter of President Trump, best known for introducing Jared Kushner to [[mohammed-bin-salman|Mohammed bin Salman]] — then Saudi defense minister — in December 2016, after Trump's first presidential victory.[n] On that reading Barrack is also most likely responsible for piecing together the [[abraham-accords|Abraham Accords]], given his extensive network of contacts in Saudi Arabia, the United Arab Emirates, and [[qatar|Qatar]].[n] The same commentary noted that Barrack had been prosecuted by the Biden Justice Department on nine felony charges related to alleged foreign corruption — described by Badlands as bogus — and was ultimately found not guilty on all counts.[n]

Badlands read Turkey's participation in the Syrian energy consortium as a major signal that Trump's early nod to Turkish President [[recep-tayyip-erdogan|Erdogan]] after the collapse of the Assad regime in December had been an attempt to give Ankara an edge over [[benjamin-netanyahu|Netanyahu]] and Israel in the contest for influence over Damascus and southern Syria.[n]""")

merge("entities/american-bar-association.md", u"""## DOJ ends ABA vetting of judicial nominees (May 2025)

On Thursday, May 29, 2025, Attorney General [[pam-bondi|Pam Bondi]] sent a letter to the American Bar Association announcing that the Justice Department would no longer vet judicial nominees through the group because of its alleged bias.[n] The letter followed the ABA's practice of rating President [[donald-trump|Trump]]'s nominees "unqualified" more often than those of other administrations, though the vast majority of his nominees were nonetheless approved by the association.[n]

Bondi accused the ABA of failing to correct the bias in its ratings and said the administration would no longer treat it differently from other organizations, while acknowledging it remained free to comment on nominations.[n] "Unfortunately, the ABA no longer functions as a fair arbiter of nominees' qualifications, and its ratings invariably and demonstrably favor nominees put forth by Democratic administrations," she wrote to ABA President William Bay, adding that "there is no justification for treating the ABA differently from such other activist organizations and the [DOJ] will not do so."[n] The changes included revoking the ABA's access to certain non-public information about nominees and barring nominees from sitting for interviews with the association or answering its written questions.[n]

## Badlands reaction

[[ashe-in-america|Ashe in America]] called the move "definitely a win," writing that through her own court experience she had learned there is broad consensus that the bar incentivizes behavior contrary to the ends of justice and that its rewards and punishments are asymmetrical and often political.[n] She characterized the outcome as reducing the ABA to "just another leftist NGO," asked whether the ACLU could be next, and predicted that partisan non-governmental organizations would eventually lose their tax statuses and their special privileges in court.[n]""")

merge("entities/pam-bondi.md", u"""## Termination of ABA judicial-nominee vetting (May 2025)

On May 29, 2025, Attorney General Bondi sent a letter to the [[american-bar-association|American Bar Association]] informing it that the Justice Department would no longer vet judicial nominees through the group, citing its alleged bias in rating nominees.[n] Bondi wrote to ABA President William Bay that "the ABA no longer functions as a fair arbiter of nominees' qualifications, and its ratings invariably and demonstrably favor nominees put forth by Democratic administrations," and that there was "no justification for treating the ABA differently from such other activist organizations."[n] The policy revoked the association's access to certain non-public information about nominees and ended the practice of having nominees interview with or answer questions from the ABA, while leaving it free to comment publicly like any other group.[n] Badlands commentary treated the decision as a clear win and a precedent for stripping other partisan NGOs of privileged standing.[n]""")

merge("entities/chevron.md", u"""## Venezuela asset waiver (May 2025)

In late May 2025 the [[trump-administration|Trump administration]] decided to let Chevron keep its key infrastructure in Venezuela while standing firm on barring the Houston-based company from importing oil extracted from [[nicolas-maduro|Nicolás Maduro]]'s government.[n] Chevron had previously faced a deadline of Tuesday, May 27, to remove all of its assets from the country after President [[donald-trump|Trump]] announced in February that he would let a Biden-era importation license expire.[n]

The new arrangement allowed the company to maintain roughly $7 billion worth of equipment in Venezuela through a narrowly tailored sanctions waiver, according to a senior White House official.[n] "It will be renegotiated so that Chevron equipment can remain, but no (money) for Maduro, which was the issue," the official said.[n] The waiver, first reported by Bloomberg, permitted essential upkeep but not energy exploration.[n]

Badlands commentary reported that Richard Grenell's plan was to "wait out" Secretary of State [[marco-rubio|Marco Rubio]] — a staunch Maduro critic who advised Trump on the waiver — and to push the White House to let the oil flow again once Rubio was no longer serving in the administration.[n] [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] read this as further signal of a growing rift inside the administration between establishment NeoCon Republicans such as Rubio and the figures who came to Washington with Trump, such as Grenell.[n]""")

merge("entities/us-court-of-appeals-for-the-federal-circuit.md", u"""## Temporary reinstatement of the Trump tariffs (May 2025)

On Thursday, May 29, 2025, the Federal Circuit temporarily reinstated tariffs imposed by President [[donald-trump|Donald Trump]], granting the administration's request to pause a lower-court ruling that had struck them down.[n] The decision put on hold a Wednesday-night order from the [[us-court-of-international-trade|U.S. Court of International Trade]] that had blocked enforcement of most of the contested tariffs; the appellate court said the ruling was "temporarily stayed until further notice while this court considers the motions papers."[n] The administration had warned it would seek emergency relief from the Supreme Court as soon as Friday if the tariffs were not promptly restored.[n]

The underlying litigation comprised two suits — one from a coalition of companies including V.O.S. Selections, Inc., and another from states including Oregon, New York, and Illinois — arguing that the tariffs were improperly enacted via executive order.[n] Under the Federal Circuit's schedule, plaintiffs were to respond to the government's motion by June 5 with a reply due June 9, and both sides were required to keep the court updated on related activity in the lower court.[n]""")

merge("entities/kash-patel.md", u"""## Surge in threats against Trump attributed to Comey post (May 2025)

In late May 2025, FBI Director Patel disclosed that the [[fbi|Bureau]] had been inundated with threats against President [[donald-trump|Donald Trump]]'s life, which he attributed to a controversial Instagram post by former FBI Director [[james-comey|James Comey]].[n] Speaking to Bret Baier, Patel explained that the post — depicting shells arranged to form the numbers "86 47" — had produced a surge in "copycat" incidents.[n] The term "86" is commonly used in hospitality to mean "get rid of" something but can also be read as a mob reference to a grave eight feet long and six feet deep, while 47 refers to Trump's status as the 47th president; Comey claimed he was unaware of the violent connotations despite his long law-enforcement career.[n]

Patel expressed frustration at the strain on Bureau resources, asking, "Do you know how many agents I've had to take offline from chasing down child sex predators, fentanyl traffickers, terrorists?"[n] He suggested the post had inspired people across the country to make threats in the belief that such behavior was permissible because Comey had done it.[n] The Bureau did not provide specific details about the threats; the disclosure came less than a year after a gunman's bullet struck Trump's ear at a campaign event in Pennsylvania.[n]""")

merge("entities/laura-loomer.md", u"""## Call to deport Xi Jinping's daughter (May 2025)

On Wednesday, May 28, 2025, Loomer called for the deportation of Chinese President [[xi-jinping|Xi Jinping]]'s daughter, Xi Mingze, in the wake of the [[trump-administration|Trump administration]]'s move to revoke the visas of some Chinese students, particularly those linked to the Chinese Communist Party.[n] Citing the Financial Express, Loomer said Xi Mingze had previously attended [[harvard-university|Harvard University]].[n] "DEPORT XI JINPING'S DAUGHTER! She lives in Massachusetts and went to Harvard! Sources tell me PLA guards from the CCP provide her with private security on US soil in Massachusetts!" she wrote on X.[n] The post came hours after Secretary of State [[marco-rubio|Marco Rubio]] announced the administration would "aggressively" revoke visas for students from China.[n]

Badlands contributor [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] pushed back, arguing that Loomer did not appear to know Xi's origin story — that his parents were persecuted by the communist party, that his father sought to open China's markets, and that since taking power Xi has hunted down and imprisoned what Badlands describes as the worst communist leaders in China.[n] The same commentary asserted that President [[donald-trump|Trump]] and Xi are genuine friends who discuss their children and grandchildren when they meet.[n]""")

merge("entities/jake-tapper.md", u"""## Ratings collapse amid the "Original Sin" book tour (May 2025)

In May 2025, Tapper recorded his lowest-rated month at [[cnn|CNN]] in nearly a decade, despite a whirlwind publicity tour that generated an onslaught of attention.[n] The book he wrote with Axios reporter Alex Thompson — "Original Sin: President Biden's Decline, Its Cover-Up, and His Disastrous Choice to Run Again" — was released that month to considerable fanfare and helped set the news cycle with fresh accusations that the Biden White House had hidden the truth about the former president's fitness for office.[n] Tapper promoted the project across podcasts, talk shows, and cable news, and the book was pushed relentlessly on CNN, but the spotlight failed to translate into viewership.[n]

## Badlands commentary

[[ashe-in-america|Ashe in America]] argued that Tapper's ratings were failing because he was still lying to the American people, continuing to sell the idea that the Biden White House had fooled everyone and that the press bore no responsibility for its own reporting.[n] She summarized his implicit defense as "Don't blame us! We're too stupid to have gotten the story right," and contended that the press corps was not stupid but rather attempting to avoid criminal exposure for complicity.[n] [[jon-herold|Jon Herold]] called the "Jake Tapper retribution tour" pathetic, observing that alternative media was refusing to let him off the hook while regime media was doing so, and that it had never been easier to tell the two apart.[n]""")

merge("entities/marco-rubio.md", u"""## State Department reorganization notice to Congress (May 2025)

In late May 2025, Rubio spearheaded a reorganization of the [[state-department|State Department]] set to eliminate or consolidate more than 300 of the agency's offices and bureaus.[n] He had first announced plans in April to restructure the department on the grounds that it was "bloated, bureaucratic, and unable to perform its essential diplomatic mission."[n] The department submitted a notice to [[congress|Congress]] on Thursday, May 29, disclosing the overhaul, which senior officials described to Fox News Digital as the largest restructuring of the agency since the Cold War.[n] The congressional notice said the plan aimed to cut red tape so the department could respond to threats more quickly, place greater emphasis on its primary mission of representing the United States abroad, and eliminate "bureaucratic overgrowth" in Washington.[n] One senior official put it bluntly: "We have too many godd--- offices. We're trying to shrink offices rather than create them."[n]

## Chinese student visas and the Venezuela waiver dispute

On May 28, 2025, Rubio announced that the administration would "aggressively" revoke visas for students from China, especially those linked to the Chinese Communist Party — an announcement that preceded [[laura-loomer|Laura Loomer]]'s call to deport [[xi-jinping|Xi Jinping]]'s daughter.[n]

Rubio also figured in the internal debate over Venezuela policy. As a staunch critic of [[nicolas-maduro|Nicolás Maduro]], he advised President [[donald-trump|Trump]] on the narrowly tailored sanctions waiver that let [[chevron|Chevron]] keep roughly $7 billion of equipment in Venezuela while continuing to bar oil imports.[n] Badlands reported that Richard Grenell's strategy was to "wait out" Rubio and press the White House to let the oil flow again once the Floridian left the administration, a dynamic [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] read as evidence of a growing rift between establishment NeoCon Republicans and the Trump loyalists.[n]""")
