import io,os,re,subprocess,sys
BASE=r"C:/Users/14053/hermes-projects/badlands-substack"
sys.path.insert(0,BASE+"/scripts")
LOCK=BASE+"/scripts/wiki_page_lock.py"
MERGE=BASE+"/scripts/f4c_merge.py"
import time

SEC={
"federal-reserve-bank-of-new-york":("## Project Cedar (2022–2023)","""The New York Federal Reserve sponsored [[project-cedar|Project Cedar]], a pilot program agreed to on November 15, 2022 by several of the world's biggest banks — including Wells Fargo, Citigroup, HSBC and Mastercard — that would convert regular U.S. dollars into a new type of dollar.[{n}] Coverage summarized in the [[badlands-news-brief|Badlands News Brief]] characterized the plan as one that could lead to a complete overthrow of the U.S. dollar as currently understood, and Badlands commentary tied it, alongside [[executive-order-14067|Executive Order 14067]], to a possible trackable [[central-bank-digital-currency|central bank digital currency]].[{n}]"""),
"blackrock":("## ESG backlash (January 2023)","""By January 2023 BlackRock, the world's biggest asset manager, faced increasing backlash over environmental, social and governance investing, with a handful of U.S. states pulling billions of dollars from BlackRock funds over accusations of \"greenwashing,\" harming the fossil fuel industry and turbocharging America's \"woke\" culture.[{n}] At the [[world-economic-forum|World Economic Forum]] in Davos, chief executive [[larry-fink|Larry Fink]] said the [[esg|ESG]] narrative had been tarnished and had become \"ugly\" and personal.[{n}]"""),
"larry-fink":("## Davos 2023 ESG remarks","""Speaking to Bloomberg TV at the [[world-economic-forum|World Economic Forum]] in Davos on January 17, 2023, Fink said of [[esg|ESG]] investing: \"Let's be clear, the narrative is ugly, the narrative is creating this huge polarization.\"[{n}] He added that [[blackrock|BlackRock]] was \"trying to address the misconceptions,\" that it was hard \"because it's not business any more, they're doing it in a personal way,\" and that for the first time in his professional career \"attacks are now personal\" with critics trying to \"demonize the issues.\"[{n}] [[ryan-delarme|Ryan DeLarme]] characterized ESG in the [[badlands-news-brief|Badlands News Brief]] as a China-inspired scoring system — a social credit system for corporations measuring adherence to globalist agendas rather than obedience to the CCP — and noted that independent media outlets and America First politicians had spent the previous year attacking the concept.[{n}]"""),
"klaus-schwab":("## Staff mutiny reporting (January 2023)","""In January 2023 The Guardian reported that the future of Schwab — \"Mr Davos\" for more than half a century — had become a talking point at that year's meeting after [[world-economic-forum|World Economic Forum]] employees voiced strong criticism of their chair and of the lack of a succession strategy.[{n}] A group of current and former WEF staff who contacted the paper said the 82-year-old Schwab was a law unto himself and had surrounded himself with \"nobodies\" incapable of running the organisation he founded in the early 1970s.[{n}] The group said: \"Klaus has been at the helm of the WEF for 52 years. When he was born [in 1938] 122 of the 195 states in the world right now did not even exist. He is completely unaccountable to anyone inside and outside the organisation.\"[{n}] [[jordan-sather|Jordan Sather]] commented that the WEF appeared to be in shambles, with staff describing Schwab as running the organization as though he had a God complex and hiring inept people, while reporting that week indicated many companies and NGOs bankrolling the forum were unhappy with his management.[{n}]"""),
"world-economic-forum":("## 2023 annual meeting and internal criticism","""At the January 2023 Davos meeting, the WEF faced internal dissent: current and former staff told The Guardian that founder and chair [[klaus-schwab|Klaus Schwab]] was unaccountable, had led the body for 52 years, and had surrounded himself with people incapable of running it, with no succession strategy in place.[{n}] Reporting that week also indicated that many of the companies and NGOs bankrolling the forum were unhappy with Schwab's management.[{n}] The same meeting produced [[larry-fink|Larry Fink]]'s remarks that the [[esg|ESG]] narrative had turned \"ugly\" and personal, and Saudi finance minister [[mohammed-al-jadaan|Mohammed Al-Jadaan]]'s statement that the kingdom was open to settling trade in currencies other than the U.S. dollar.[{n}]"""),
"jacinda-ardern":("## Resignation announcement (January 2023)","""On January 18, 2023, Ardern tearfully announced she would step down as prime minister of New Zealand by February 7, after more than five years as leader, saying she lacked the energy for the job ahead of an election later that year.[{n}] \"I believe that leading a country is the most privileged job anyone could ever have, but also one of the more challenging,\" she said. \"You cannot and should not do it unless you have a full tank plus a bit in reserve for those unexpected challenges.\"[{n}] She added that she knew what the job takes and no longer had \"enough in the tank to do it justice,\" but believed others around her did, and called the period \"the most fulfilling five and a half years of my life.\"[{n}] ZeroHedge described her as one of the best known faces of the globalist push that overrode personal rights and liberties during what it called \"covid fascism.\"[{n}] [[burning-bright|Burning Bright]] wrote in the [[badlands-news-brief|Badlands News Brief]] that while her departure was welcome news, citizen journalists and political leaders in New Zealand and beyond must ensure that such abuse of power is not simply consigned to history and that Ardern is among many world leaders brought before legal bodies for a proper accounting.[{n}]"""),
"sheila-jackson-lee":("## Leading Against White Supremacy Act of 2023","""In January 2023 Jackson Lee introduced the [[leading-against-white-supremacy-act-of-2023|Leading Against White Supremacy Act of 2023]], a House bill in the 118th Congress that would criminalize social media postings supporting \"white supremacy\" or replacement theory.[{n}] Law professor [[jonathan-turley|Jonathan Turley]] called the measure \"an almost impenetrable word salad of convoluted provisions\" that would gut the [[first-amendment|First Amendment]] and create effective thought crimes, while predicting it would not pass.[{n}]"""),
"jonathan-turley":("## Criticism of the Leading Against White Supremacy Act (2023)","""In a January 2023 post, Turley criticized the [[leading-against-white-supremacy-act-of-2023|Leading Against White Supremacy Act of 2023]], introduced by Rep. [[sheila-jackson-lee|Sheila Jackson Lee]], as an almost impenetrable word salad whose one clear effect would be to gut the [[first-amendment|First Amendment]] and create effective thought crimes.[{n}] He wrote that the anti-free-speech movement in the United States continues to grow with alarming speed among writers, journalists, academics and most importantly Democratic members of Congress, who now openly call for censorship and for manipulation of what citizens see and read.[{n}] Although he expected the bill to fail, he said its provisions were deeply disturbing because they reflect successful speech-criminalization efforts abroad and echo a bill he had testified against in the Senate the prior year.[{n}]"""),
"karine-jean-pierre":("## January 2023 briefing on the Biden documents scandal","""On January 18, 2023, reporters again pressed Jean-Pierre about the classified documents stored in President Biden's garage as part of the [[biden-classified-documents-scandal|Biden classified documents scandal]].[{n}] NBC's Peter Alexander noted that the Justice Department had not told the [[white-house|White House]] it could not discuss the facts underlying the special counsel investigation and asked why she could not speak to them; Jean-Pierre replied that \"we've been clear\" and later referred him to the White House counsel's office.[{n}] Alexander accused the Biden White House of withholding information, asking whether she would concede the White House had been incomplete in its provision of information.[{n}] [[justin-deschamps|Justin Deschamps]] wrote that she had run one of the most useless press conferences of the period, answering zero questions and repeatedly deflecting.[{n}]"""),
"marjorie-taylor-greene":("## House Oversight Committee appointment (2023)","""In January 2023 the [[white-house|White House]] denounced the appointment of Greene and Rep. [[paul-gosar|Paul Gosar]] to the [[house-oversight-committee|House Oversight Committee]], with spokesperson Ian Sams suggesting the assignments showed House Republicans were setting the stage for \"divorced-from-reality political stunts\" rather than bipartisan work, and demanding that GOP leaders reveal what secret deals were made with \"extreme MAGA members\" to elect a Speaker.[{n}] [[ryan-delarme|Ryan DeLarme]] countered that the committee was stacked with America First firebrands, some previously stripped of assignments by the prior Congress, and would investigate legitimate concerns including fentanyl crossing the border, the Afghanistan withdrawal, COVID-19 origins and Biden family influence peddling.[{n}]"""),
"paul-gosar":("## House Oversight Committee appointment (2023)","""In January 2023 the [[white-house|White House]] criticized the appointment of Gosar and Rep. [[marjorie-taylor-greene|Marjorie Taylor Greene]] to the [[house-oversight-committee|House Oversight Committee]], saying through spokesperson Ian Sams that the Biden administration stood ready to accommodate legitimate oversight needs but that the assignments suggested political theatrics instead.[{n}] Badlands commentary argued the committee would pursue substantive investigations into border fentanyl, the botched Afghanistan withdrawal, COVID-19 origins and Biden family influence peddling.[{n}]"""),
"house-oversight-committee":("## 2023 membership dispute","""In January 2023 the [[white-house|White House]] publicly denounced the appointment of Republican Reps. [[marjorie-taylor-greene|Marjorie Taylor Greene]] of Georgia and [[paul-gosar|Paul Gosar]] of Arizona to the committee, with spokesperson Ian Sams saying House Republicans appeared to be setting the stage for \"divorced-from-reality political stunts\" and calling on GOP leaders to disclose what secret deals were struck with \"extreme MAGA members\" to elect a Speaker.[{n}] [[ryan-delarme|Ryan DeLarme]] responded that the panel was a \"dream team of America First firebrands,\" contrasted it with the January 6 committee, and listed its likely subjects as fentanyl trafficking across the border, the Afghanistan withdrawal, COVID-19 origins and Biden family influence peddling.[{n}]"""),
"saudi-arabia":("## Openness to non-dollar trade settlement (2023)","""In January 2023 finance minister [[mohammed-al-jadaan|Mohammed Al-Jadaan]] told Bloomberg TV in Davos that the kingdom was open to discussions about settling trade in currencies other than the U.S. dollar, naming the euro and the Saudi riyal as possibilities and saying he would not rule out any discussion that improves world trade.[{n}] [[burning-bright|Burning Bright]] argued that with the formation of the [[brics|BRICS]] alliance and Saudi Arabia's continued flirtation with joining it, the era of [[petrodollar|petrodollar]] hegemony appeared to be ending.[{n}]"""),
"brics":("## Saudi Arabia and de-dollarization (2023)","""Badlands commentary in January 2023 linked the formation of the BRICS alliance to Saudi finance minister [[mohammed-al-jadaan|Mohammed Al-Jadaan]]'s statement that [[saudi-arabia|Saudi Arabia]] was open to settling trade in currencies other than the U.S. dollar, arguing that with the kingdom's continued flirtation with joining BRICS the time of [[petrodollar|petrodollar]] and Deep State hegemony appeared to be on the verge of ending.[{n}]"""),
"central-bank-digital-currency":("## Project Cedar and Executive Order 14067","""In January 2023 the [[badlands-news-brief|Badlands News Brief]] highlighted the [[federal-reserve-bank-of-new-york|New York Federal Reserve]]-sponsored [[project-cedar|Project Cedar]] pilot, agreed to in November 2022 by banks including Wells Fargo, Citigroup, HSBC and Mastercard, as a possible pathway to a new type of U.S. dollar.[{n}] [[ryan-delarme|Ryan DeLarme]], citing macroeconomist and CIA advisor [[jim-rickards|Jim Rickards]], wrote that Project Cedar together with [[executive-order-14067|Executive Order 14067]] could be one of several avenues leading to a new currency, and that overthrowing the U.S. dollar in favor of a trackable central bank digital currency was a critical part of the Davos agenda.[{n}]"""),
"esg":("## Larry Fink's \"demonized\" narrative remarks (2023)","""By January 2023 [[blackrock|BlackRock]] faced growing backlash over ESG investing, with several U.S. states pulling billions of dollars from its funds over accusations of greenwashing, damaging the fossil fuel industry and promoting \"woke\" culture.[{n}] At Davos, chief executive [[larry-fink|Larry Fink]] told Bloomberg TV that the narrative had become \"ugly\" and was \"creating this huge polarization,\" that BlackRock was trying to address misconceptions, and that for the first time in his career attacks had become personal, with critics seeking to \"demonize the issues.\"[{n}] [[ryan-delarme|Ryan DeLarme]] described ESG as a China-inspired system analogous to a social credit score for corporations, measuring adherence to globalist agendas, and noted that independent media and America First politicians had seized on the concept over the previous year.[{n}]"""),
"stakeholder-capitalism":("## Stakeholder geopolitics (2023)","""A January 2023 Foreign Affairs essay, \"The Dawn of Stakeholder Geopolitics,\" argued that the world had slid from cooperation to competition to conflict, that the post–Cold War order had been replaced by intensifying rivalry and then war in Europe, and that leaders must manage geopolitical competition in ways that preserve space to align with diverse parties on shared interests.[{n}] It drew lessons from the private sector's embrace of stakeholder capitalism, noting that while governments retreated from cooperation the business community came together on common challenges while still competing in the marketplace.[{n}] [[chris-paul|Chris Paul]] defined stakeholder capitalism as the fusion of government with corporations through \"public-private partnerships\" with transnational corporations willing to advance the global agenda in exchange for [[esg|ESG]] investments and monopoly or cartel control — in his view the traditional definition of fascism — and read stakeholder geopolitics as world governments aligning on that agenda while non-participatory governments face cascading \"threats.\"[{n}]"""),
"petrodollar":("## 2023 Saudi signals","""In January 2023 Saudi finance minister [[mohammed-al-jadaan|Mohammed Al-Jadaan]] said in Davos that [[saudi-arabia|Saudi Arabia]] was open to discussing trade settlement in currencies besides the U.S. dollar, including the euro and the riyal.[{n}] [[burning-bright|Burning Bright]] wrote that with the formation of the [[brics|BRICS]] alliance and the kingdom's flirtation with membership, the time of petrodollar — and Deep State — hegemony appeared to be on the verge of ending, in a framing that also called for the [[federal-reserve|Federal Reserve]] and the fiat central banking system to be reformed or dismantled.[{n}]"""),
"first-amendment":("## Leading Against White Supremacy Act (2023)","""In January 2023 law professor [[jonathan-turley|Jonathan Turley]] warned that the [[leading-against-white-supremacy-act-of-2023|Leading Against White Supremacy Act of 2023]], introduced by Rep. [[sheila-jackson-lee|Sheila Jackson Lee]], would gut the First Amendment and create effective thought crimes by criminalizing social media postings deemed supportive of white supremacy or replacement theory.[{n}] He tied the bill to a broader anti-free-speech movement among writers, journalists, academics and Democratic members of Congress who openly call for censorship.[{n}]"""),
"biden-classified-documents-scandal":("## January 18, 2023 press briefing","""On January 18, 2023, reporters bombarded White House press secretary [[karine-jean-pierre|Karine Jean-Pierre]] with questions about the classified documents stored in President Biden's garage.[{n}] NBC's Peter Alexander pressed her on why the [[white-house|White House]] could not discuss the facts underlying the special counsel investigation given that the Justice Department had not barred it from doing so, and accused the administration of withholding information; Jean-Pierre said \"we've been clear\" and referred him to the White House counsel's office.[{n}]"""),
"white-house":("## January 2023 flashpoints","""In January 2023 the White House press operation came under sustained questioning over the [[biden-classified-documents-scandal|Biden classified documents scandal]], with press secretary [[karine-jean-pierre|Karine Jean-Pierre]] deflecting reporters' questions about documents found in the president's garage and referring them to the White House counsel's office.[{n}] The same week, White House spokesperson Ian Sams denounced the appointment of Reps. [[marjorie-taylor-greene|Marjorie Taylor Greene]] and [[paul-gosar|Paul Gosar]] to the [[house-oversight-committee|House Oversight Committee]], saying the administration stood ready to accommodate legitimate oversight but that House Republicans appeared to be preparing \"divorced-from-reality political stunts.\"[{n}]"""),
"federal-reserve":("## Criticism amid de-dollarization (2023)","""Commentary in the January 2023 [[badlands-news-brief|Badlands News Brief]] held that the Federal Reserve and the fiat central banking system as a whole must be reformed, torn down or scattered to the winds for humanity to move into a more sovereign, freedom-minded future in which production and free trade anchor a multi-polar world order.[{n}] The [[federal-reserve-bank-of-new-york|New York Federal Reserve]]'s sponsorship of the [[project-cedar|Project Cedar]] digital dollar pilot was cited in the same brief as a possible step toward a trackable [[central-bank-digital-currency|central bank digital currency]].[{n}]"""),
"badlands-news-brief":("## January 19, 2023 edition: \"Dollars, Saudis and Globalist Elites\"","""The January 19, 2023 edition covered news from Wednesday, January 18, including the [[project-cedar|Project Cedar]] digital dollar pilot, Rep. [[sheila-jackson-lee|Sheila Jackson Lee]]'s [[leading-against-white-supremacy-act-of-2023|Leading Against White Supremacy Act of 2023]], staff mutiny at the [[world-economic-forum|World Economic Forum]] over [[klaus-schwab|Klaus Schwab]], [[saudi-arabia|Saudi Arabia]]'s openness to non-dollar trade settlement, [[larry-fink|Larry Fink]]'s Davos remarks on [[esg|ESG]], the resignation of [[jacinda-ardern|Jacinda Ardern]], a Foreign Affairs essay on [[stakeholder-capitalism|stakeholder]] geopolitics, [[karine-jean-pierre|Karine Jean-Pierre]]'s combative briefing on the [[biden-classified-documents-scandal|Biden classified documents scandal]], and the [[white-house|White House]] response to Republican appointments to the [[house-oversight-committee|House Oversight Committee]].[{n}] Commentary came from [[ryan-delarme|Ryan DeLarme]], [[justin-deschamps|Justin Deschamps]], [[jordan-sather|Jordan Sather]], [[burning-bright|Burning Bright]] and [[chris-paul|Chris Paul]].[{n}]"""),
}

for slug,(head,body) in SEC.items():
    for attempt in range(20):
        r=subprocess.run([sys.executable,LOCK,"acquire",slug],capture_output=True,text=True)
        if r.returncode==0: break
        time.sleep(3)
    else:
        print("LOCKFAIL",slug); continue
    try:
        m=subprocess.run([sys.executable,MERGE,slug],capture_output=True,text=True)
        out=m.stdout.strip().splitlines()[-1] if m.stdout.strip() else ""
        if not out.isdigit():
            print("ERR",slug,m.stdout,m.stderr); continue
        n=int(out)
        path=None
        for d in ("entities","concepts"):
            q=os.path.join(BASE,"wiki",d,slug+".md")
            if os.path.exists(q): path=q
        t=io.open(path,encoding="utf-8").read()
        idx=t.rfind("## References")
        sec="\n"+head+"\n\n"+body.format(n=n)+"\n\n"
        t=t[:idx]+sec+t[idx:]
        io.open(path,"w",encoding="utf-8",newline="\n").write(t)
        print("OK",slug,n)
    finally:
        subprocess.run([sys.executable,LOCK,"release",slug],capture_output=True,text=True)
