import sys, re, subprocess
BASE = r'C:/Users/14053/hermes-projects/badlands-substack'
RAW = 'badlands-news-brief-5c8'
REFLINE = 'Badlands Brief — "Badlands News Brief: A Coming Conclave & More Musical Chairs", URL: https://badlands.substack.com/p/badlands-news-brief-5c8'

import time
def run(slug, folder, heading, body):
    path = f'{BASE}/wiki/{folder}/{slug}.md'
    for attempt in range(6):
        lock = subprocess.run([sys.executable, f'{BASE}/scripts/wiki_page_lock.py', 'acquire', slug],
                              capture_output=True, text=True)
        if lock.returncode == 0:
            break
        time.sleep(5)
    else:
        print('BUSY', slug); return
    try:
        t = open(path, encoding='utf-8').read()
        m = re.search(r'^sources: \[(.*?)\]\s*$', t, re.M)
        srcs = [s.strip() for s in m.group(1).split(',') if s.strip()]
        tag = 'raw/%s.md' % RAW
        if tag not in srcs:
            srcs.append(tag)
        n = str(srcs.index(tag) + 1)
        t = t[:m.start()] + 'sources: [%s]' % ', '.join(srcs) + t[m.end():]
        t = re.sub(r'^updated:.*$', 'updated: 2026-08-06', t, count=1, flags=re.M)
        sec = '\n## ' + heading + '\n\n' + body.replace('[N]', '[%s]' % n).strip() + '\n'
        if '## References' in t:
            idx = t.index('## References')
            head, tail = t[:idx], t[idx:]
            lines = tail.rstrip().split('\n')
            if not any(RAW in l for l in lines):
                lines.append('%s. %s' % (n, REFLINE))
            t = head.rstrip() + '\n\n' + sec + '\n' + '\n'.join(lines) + '\n'
        else:
            t = t.rstrip() + '\n\n' + sec + '\n## References\n\n%s. %s\n' % (n, REFLINE)
        open(path, 'w', encoding='utf-8', newline='').write(t)
        print('OK', slug, n)
    finally:
        subprocess.run([sys.executable, f'{BASE}/scripts/wiki_page_lock.py', 'release', slug])

E = [
("pope-francis","entities","Death (April 2025)","""Pope Francis died on April 21, 2025 at the age of 88, one day after making an Easter Sunday appearance at St. Peter's Square where he offered well-wishes to thousands of Catholic supporters; the [[vatican|Vatican]] said he died following a stroke.[N] Born Jorge Mario Bergoglio, he had been elected in 2013 after Benedict XVI became the first pope in roughly 600 years to resign, and he was the first Latin American pontiff and TIME's 2013 Person of the Year.[N] Over his pontificate he was known for personal humility and repeated calls for peace during the COVID-19 pandemic and the Gaza humanitarian crisis.[N] His death opened the interregnum, or *sede vacante*, and set in motion the [[papal-conclave|conclave]] process.[N] Badlands commentary surrounding the death noted that [[jd-vance|JD Vance]] had visited Francis only hours before the announcement, recalled Archbishop Vigano's scathing criticism of Bergoglio, and revisited the 2017 conflict between the pope and the Knights of Malta; [[donald-trump|President Trump]] ordered flags lowered worldwide.[N]"""),
("vatican","entities","Interregnum After the Death of Pope Francis (2025)","""The Vatican announced on Monday, April 21, 2025 that [[pope-francis|Pope Francis]] had died at 88 after a stroke, a day after his Easter appearance at St. Peter's Square.[N] His death began the leadership transition known as the interregnum, during which there is no pope in power — a period referred to as *sede vacante*, the "vacant seat."[N] Traditional Vatican practice calls for nine days of mourning, the *novendiales*, after which the election of a successor begins between 15 and 20 days from the death, organized by the camerlengo in the process known as the [[papal-conclave|conclave]].[N]"""),
("jerome-powell","entities","Trump Removal Speculation (April 2025)","""In April 2025 speculation intensified that [[donald-trump|President Trump]] would attempt to fire Powell as [[federal-reserve|Federal Reserve]] chair before his term expired in May 2026, with Trump publicly deriding him as "Mr. Too Late [to lower interest rates], a major loser."[N] Commentary in The New Republic argued that such a removal would not be truly unprecedented — although no president had ever fired a Fed chair, Trump had already removed roughly a dozen officials at nominally independent agencies including the Privacy and Civil Liberties Oversight Board, the Equal Employment Opportunity Commission, the Federal Trade Commission, the National Labor Relations Board, the Federal Election Commission, the Office of Special Counsel, the Merit Systems Protection Board, the Federal Labor Relations Authority and the [[consumer-financial-protection-bureau|Consumer Financial Protection Bureau]] — and predicted the Supreme Court would permit it.[N] Markets reacted where they had not to earlier firings: after [[kevin-hassett|Kevin Hassett]] said the administration was still studying options for removing Powell, the dollar index collapsed to a fresh three-year low in thin Asian holiday trading while gold hit an all-time high and Bitcoin spiked.[N] Hassett accused the Powell Fed of acting politically, raising rates after Trump's first election and cutting them just before the 2024 vote while staying silent on what he called textbook inflationary spending under Joe Biden.[N] Badlands commentator Jon Herold argued the feud was self-resolving: if Powell would not cut rates, Trump's browbeating and firing threats would crash the dollar low enough to deliver financial easing anyway.[N]"""),
("federal-reserve","entities","Trump Pressure Campaign (April 2025)","""In April 2025 the Fed became the central front of a public confrontation with [[donald-trump|President Trump]], who threatened to fire Chair [[jerome-powell|Jerome Powell]] well before the end of his term in May 2026.[N] Critics noted the Fed is an independent agency, but Trump had already dismissed officials at a series of nominally independent bodies, and commentary predicted the Supreme Court would sustain a Powell removal.[N] Markets that had ignored earlier firings responded sharply to Powell speculation: the dollar index fell to a three-year low, gold reached a record and [[bitcoin|Bitcoin]] spiked after [[kevin-hassett|Kevin Hassett]] confirmed the administration was still exploring removal options.[N] Badlands commentator Burning Bright argued Trump had the Fed trapped in "game theory pincers," claimed the central bank had effectively been folded into a [[us-department-of-the-treasury|Treasury]] now run by [[scott-bessent|Scott Bessent]], and framed the 2020 COVID-era money printing as a deliberately provoked acceleration of the fiat system's timeline that exposed the link between central banking and economic strife.[N] In this reading the US economy sat in an engineered stagflationary holding pattern in which raising rates would guarantee recession and cutting them would risk an inflationary boom, while Trump's tariffs, tax breaks and onshoring were intended to produce an offsetting deflationary cycle and a shift back toward sound-money valuation in gold, Bitcoin, or both.[N]"""),
("kevin-hassett","entities","Powell Removal Comments (April 2025)","""As Director of the National Economic Council, Hassett said on Friday, April 18, 2025, when asked whether removing [[jerome-powell|Jerome Powell]] was an option, that "the president and his team will continue to study that."[N] The remark was cited by traders as the trigger for a sudden collapse of the dollar index to a three-year low in illiquid early Asian trading over the Easter holiday, alongside a record gold price and a spike in [[bitcoin|Bitcoin]].[N] Hassett further argued that the [[federal-reserve|Federal Reserve]] under Powell — a Trump first-term appointee — had acted politically to benefit Democrats, raising rates immediately after Trump's first election on the theory that supply-side tax cuts would be inflationary, declining to warn about "runaway spending" under Joe Biden, and then cutting rates just before the 2024 election.[N]"""),
("scott-bessent","entities","Badlands Framing of Treasury-Fed Consolidation (2025)","""In April 2025 Badlands commentator Burning Bright asserted that [[donald-trump|Trump]] wielded direct control over the [[federal-reserve|Federal Reserve]] as a result of first-administration moves that, in this account, folded the central bank into the [[us-department-of-the-treasury|US Treasury]] now led by Bessent.[N] The claim was offered as context for Trump's escalating public feud with Chair [[jerome-powell|Jerome Powell]] and for the argument that "preemptive cuts" would ultimately be delivered regardless of Powell's resistance.[N]"""),
("bitcoin","concepts","Powell Speculation Spike and MicroStrategy Purchases (April 2025)","""Bitcoin spiked suddenly in April 2025 alongside a record gold price and a three-year low in the dollar index, after remarks by [[kevin-hassett|Kevin Hassett]] revived speculation that [[donald-trump|President Trump]] would remove [[jerome-powell|Jerome Powell]] from the [[federal-reserve|Federal Reserve]].[N] Badlands commentary framed sound money backing — "whether you're talking about gold, Bitcoin or both" — as the endpoint of Trump's effort to pull the United States away from the fiat system after first milking it for all it was worth.[N] In the same period [[microstrategy|MicroStrategy]] disclosed in a Form 8-K to the [[securities-and-exchange-commission|SEC]] that it had bought 6,556 bitcoin for $555.8 million in cash between April 14 and April 20, 2025, at roughly $84,785 per coin; analysts at TD Cowen argued the company's purchases had little effect on the price.[N]"""),
("michael-saylor","entities","MicroStrategy Bitcoin Purchases (April 2025)","""[[microstrategy|MicroStrategy]] disclosed that it acquired 6,556 bitcoin for $555.8 million in cash between April 14 and April 20, 2025, at an average price near $84,785, while simultaneously selling 1.755 million MSTR shares for net proceeds of $547.7 million — prompting the Badlands quip that "Michael loves his ATM."[N] Analysts at TD Cowen said that if the company stopped buying [[bitcoin|Bitcoin]] entirely it would have little to no impact on the cryptocurrency's price.[N]"""),
("vladimir-putin","entities","Ratification of the Russia-Iran Strategic Partnership Treaty (April 2025)","""On Monday, April 21, 2025, Putin ratified parliamentary approval of the [[russia-iran-comprehensive-strategic-partnership-treaty|Comprehensive Strategic Partnership Agreement]] with [[iran|Iran]], which he had originally signed with President [[masoud-pezeshkian|Masoud Pezeshkian]] in January.[N] The treaty formalizes cooperation across national security, peaceful nuclear energy and joint resistance to unilateral sanctions.[N] Badlands commentary read the timing as Putin "placing himself firmly between [[benjamin-netanyahu|Netanyahu]] and Tehran," daring Israel to strike while [[donald-trump|Trump]] pressed a deal that would grant Iran a civil nuclear program.[N]"""),
("masoud-pezeshkian","entities","Comprehensive Strategic Partnership With Russia","""Pezeshkian signed the [[russia-iran-comprehensive-strategic-partnership-treaty|Comprehensive Strategic Partnership Agreement]] with [[vladimir-putin|Vladimir Putin]] in January 2025; Putin ratified the parliamentary approval and brought the treaty into force on April 21, 2025.[N] The agreement commits the two states to stronger relations across national security, peaceful nuclear energy and joint resistance to unilateral sanctions.[N]"""),
("sergey-lavrov","entities","Remarks on the Iran Treaty (April 2025)","""In the week before ratification, Foreign Minister Lavrov emphasized that the [[russia-iran-comprehensive-strategic-partnership-treaty|Comprehensive Strategic Partnership Agreement]] with [[iran|Iran]] was being finalized "despite the challenging regional and global landscape and attempts to exert pressure on our nations" by third parties.[N]"""),
("iran","entities","Russia Treaty and US Pressure (April 2025)","""On April 21, 2025 [[vladimir-putin|Vladimir Putin]] brought into force the [[russia-iran-comprehensive-strategic-partnership-treaty|Comprehensive Strategic Partnership Agreement]] he had signed with President [[masoud-pezeshkian|Masoud Pezeshkian]] in January, covering national security, peaceful nuclear energy and joint resistance to unilateral sanctions.[N] The ratification came as [[donald-trump|President Trump]] threatened military action unless Iran curtailed nuclear activities enough to guarantee it could not build weapons — an ambition the Islamic Republic has consistently denied holding.[N] Badlands commentary noted that Trump had signalled the emerging deal would grant Iran a civil nuclear energy program, a red line for Israeli politics, and criticized [[mike-huckabee|Mike Huckabee]]'s rhetoric and [[mark-levin|Mark Levin]]'s accusation that Trump was negotiating another Obama-style nuclear deal, while asking how many nuclear weapons Israel itself possesses.[N]"""),
("tren-de-aragua","entities","April 2025 RICO Indictments","""On Monday, April 21, 2025, federal authorities announced charges against more than two dozen people described as associated with Tren de Aragua, covering conduct from robbery and sex trafficking to the murder of women who tried to escape.[N] Prosecutors brought two New York indictments: one against six alleged current TdA members and another against 21 people said to belong to Anti-Tren, a splinter group.[N] The [[justice-department|Justice Department]] said these were the first indictments against TdA under the [[racketeer-influenced-and-corrupt-organizations-act|Racketeer Influenced and Corrupt Organizations Act]], and Attorney General [[pam-bondi|Pam Bondi]] called the group "not just a street gang" but "a highly structured terrorist organization."[N] The charges were framed as a rebuttal to immigration-rights advocates who argued the government was overselling the TdA threat.[N] Badlands commentary cited [[michael-flynn|General Flynn]]'s statement that TdA is "a Foreign Terrorist organization directly backed by elements inside of the Venezuelan (VE) government," and drew an analogy to [[kilmar-abrego-garcia|Abrego Garcia]] being backed by elements inside the US government rather than by the US government as such — a distinction the commentator called critical when assessing adversarial states.[N]"""),
("pam-bondi","entities","Tren de Aragua Indictments (April 2025)","""Announcing charges against 27 alleged [[tren-de-aragua|Tren de Aragua]] associates on April 21, 2025, Attorney General Bondi said the group "is not just a street gang – it is a highly structured terrorist organization that has destroyed American families with brutal violence, engaged in human trafficking, and spread deadly drugs through our communities."[N] Bondi was also among the executive officials named as defendants in [[harvard-university|Harvard University]]'s lawsuit over the freezing of federal grants and contracts.[N]"""),
("justice-department","entities","First RICO Indictments Against Tren de Aragua (2025)","""The Justice Department announced on April 21, 2025 that it had obtained two New York indictments charging 27 people connected to [[tren-de-aragua|Tren de Aragua]] and the splinter group Anti-Tren with offenses ranging from robbery and drug trafficking to sex trafficking and murder.[N] The department said these were its first indictments against TdA under the [[racketeer-influenced-and-corrupt-organizations-act|RICO]] statute.[N]"""),
("racketeer-influenced-and-corrupt-organizations-act","concepts","Use Against Tren de Aragua (2025)","""In April 2025 the [[justice-department|Justice Department]] said its two New York indictments charging 27 alleged [[tren-de-aragua|Tren de Aragua]] and Anti-Tren associates were the first brought against the Venezuelan gang under RICO.[N]"""),
("klaus-schwab","entities","Resignation as WEF Chair (April 2025)","""Schwab resigned as chair of the [[world-economic-forum|World Economic Forum]]'s board of trustees, the organization announced on Monday, April 21, 2025.[N] In a statement he said that "following my recent announcement, and as I enter my 88th year, I have decided to step down from the position of Chair and as a member of the Board of Trustees, with immediate effect"; the board accepted the resignation at an extraordinary meeting held on April 20, and Vice Chairman Peter Brabeck-Letmathe became interim chairman.[N] Badlands commentary noted the departure had first been announced on May 21, 2024, with CNBC reporting the leadership change would be completed before the January 2025 Davos gathering, so the exit took several months longer than expected; the commentary observed that Schwab had led the WEF for 50 years and argued the body should be dissolved rather than given a new leader.[N]"""),
("world-economic-forum","entities","Schwab Resignation and Interim Chairmanship (2025)","""On April 21, 2025 the Geneva-based WEF announced that founder [[klaus-schwab|Klaus Schwab]], 87, had resigned as chair of its board of trustees with immediate effect, a step it had foreshadowed earlier that month without a timeframe.[N] The board accepted the resignation at an extraordinary meeting on April 20 and named Vice Chairman Peter Brabeck-Letmathe interim chairman.[N] Badlands commentary marked the end of Schwab's 50 years at the head of the organization and argued the forum should be dissolved instead of replacing him.[N]"""),
("state-department","entities","Reported 2025 Reorganization Draft","""In April 2025 a draft order circulated within the State Department outlining a complete overhaul of the agency to "streamline mission delivery" while eliminating "waste, fraud and abuse," according to The New York Times.[N] The plan reportedly recommended eliminating the bureaus handling African affairs along with all "non-essential embassies and consulates in sub-Saharan Africa," shuttering bureaus on democracy and human rights, refugees and migration, and international organizations, abolishing the special envoy on climate, and shrinking the US diplomatic presence in Canada to a "significantly reduced team" overseen directly by Secretary [[marco-rubio|Marco Rubio]].[N] It also proposed ending the foreign service's "outdated and disorganized generalist global rotation model" in favor of specialization, and terminating the recruitment contract for fellowship candidates from Howard University.[N] Rubio called the report "fake news" in a post on X, but Politico reported that diplomats were rattled and believed the memo could be genuine.[N] Badlands commentary endorsed abolishing the department outright, arguing most international problems trace back to it, praising special envoys such as [[steve-witkoff|Steve Witkoff]] and [[adam-boehler|Adam Boehler]] as evidence that diplomacy is best conducted by businessmen and pragmatists, and describing the [[cia|CIA]] as "the heart and soul of the State Department."[N]"""),
("marco-rubio","entities","Response to the State Department Overhaul Draft (2025)","""Rubio dismissed reporting on a draft order to shutter large sections of the [[state-department|State Department]] as "fake news" in a post on X on Sunday, April 20, 2025.[N] The leaked plan would have placed a sharply reduced US diplomatic presence in Canada under his direct supervision, and despite his denial Politico reported that diplomats believed the memo could be real.[N]"""),
("cia","entities","Badlands Critique in the State Department Debate (2025)","""Commenting on reports of a plan to gut the [[state-department|State Department]] in April 2025, Badlands writer GhostofBasedPatrickHenry described the CIA as "the heart and soul of the State Department" and "a malignant tumor on humanity" that should be excised as soon as possible.[N]"""),
("insurrection-act","concepts","Border Assessment Under Trump (2025)","""On his first day back in the White House in January 2025, [[donald-trump|President Trump]] signed an executive order declaring an emergency at the US southern border and directed senior officials to evaluate whether to invoke the Insurrection Act of 1807, which allows the president to use active-duty military personnel for law-enforcement duties inside the United States.[N] Defense Secretary [[pete-hegseth|Pete Hegseth]] and Homeland Security Secretary [[kristi-noem|Kristi Noem]] were tasked with the assessment and were reported to be preparing recommendations for release in late April 2025.[N] Border crossings had reached a quarter-century low by that point, but the statute would further expand presidential power; Badlands commentary dismissed alarm over invocation as less far-fetched than "the TV narrative that nothing is going on behind the scenes."[N]"""),
("pete-hegseth","entities","Insurrection Act Assessment (2025)","""Hegseth, as Defense Secretary, was tasked together with Homeland Security Secretary [[kristi-noem|Kristi Noem]] with assessing whether [[donald-trump|President Trump]] should invoke the [[insurrection-act|Insurrection Act of 1807]] at the southern border, with recommendations reported to be due in late April 2025.[N] He was also among the executive officials named as defendants in [[harvard-university|Harvard University]]'s suit over the federal funding freeze.[N]"""),
("kristi-noem","entities","Insurrection Act Assessment (2025)","""As Homeland Security Secretary, Noem was tasked alongside Defense Secretary [[pete-hegseth|Pete Hegseth]] with evaluating whether to recommend invoking the [[insurrection-act|Insurrection Act of 1807]] in response to immigration at the southern border, with an announcement expected in late April 2025.[N]"""),
("kanye-west","entities","Walking Back Nazi Comments (April 2025)","""On Monday, April 21, 2025, Ye disavowed his earlier claims of being a Nazi in a post on X that he later deleted, writing that he had "come to the realization that I'm not a Nazi" while adding that he "can and will say whatever the f*ck I feel like whenever the f*ck I feel like it."[N] Earlier in 2025 he had proclaimed himself "a Nazi" and expressed love for Adolf Hitler following a lengthy series of anti-Semitic posts, and the previous month he had flashed a swastika t-shirt in a TMZ video that he called his "greatest dream" in another since-deleted post.[N] The fallout from these statements cost him hundreds of millions of dollars in lost corporate sponsorships.[N] Badlands commentary speculated that the episode had been an "op" that provoked establishment Republicans into passing hate-speech legislation effectively banning criticism of a specific foreign government, thereby exposing their record on free speech.[N]"""),
("harvard-university","entities","Lawsuit Over the 2025 Federal Funding Freeze","""Harvard recruited law firms and attorneys with ties to allies of [[donald-trump|President Trump]] to sue his administration over the freezing of billions of dollars in federal grants and contracts.[N] The suit, filed in federal court in Massachusetts, listed lawyers from four firms and named a long roster of executive agency officials and Trump appointees as defendants, including Health and Human Services Secretary [[robert-f-kennedy-jr|Robert F. Kennedy Jr.]], Attorney General [[pam-bondi|Pam Bondi]] and Defense Secretary [[pete-hegseth|Pete Hegseth]].[N] The complaint argued the freeze would disrupt research developing drugs for Parkinson's and Alzheimer's diseases, nanofibers to protect servicemembers and first responders, support for astronauts, and an artificial intelligence system for diagnosing and treating cancer.[N] Among the firms was Quinn Emanuel, a Los Angeles-headquartered practice that has long represented [[elon-musk|Elon Musk]], who donated $250 million to Trump's campaign and became the public face of the White House [[doge|DOGE]] office.[N]"""),
("mahmoud-khalil","entities","Denial of Furlough for Son's Birth (April 2025)","""Khalil, the [[columbia-university|Columbia University]] graduate detained by [[immigration-and-customs-enforcement|Immigration and Customs Enforcement]], was denied permission to attend the birth of his first child, several outlets confirmed on Monday, April 21, 2025.[N] His attorneys had written on the Sunday to Melissa Harper, director of ICE's New Orleans field office where he was held, requesting a two-week release to be with his wife for the delivery; Harper denied the request about 30 minutes later, dismissing the furlough "after consideration of the submitted information and a review" of his case.[N] His wife, Dr. Noor Abdalla, said she welcomed their son into the world alone and called it "a purposeful decision by ICE to make me, Mahmoud, and our son suffer."[N]"""),
("immigration-and-customs-enforcement","entities","Denial of Mahmoud Khalil's Furlough Request (2025)","""In April 2025 ICE denied a two-week furlough request from [[mahmoud-khalil|Mahmoud Khalil]], detained at its New Orleans field office, to attend the birth of his first child; field office director Melissa Harper rejected the request roughly 30 minutes after receiving it.[N] Khalil's wife, Dr. Noor Abdalla, gave birth alone and described the refusal as "a purposeful decision by ICE to make me, Mahmoud, and our son suffer."[N]"""),
("donald-trump","entities","Powell Feud, Easter Messaging and Border Powers (April 2025)","""Through April 2025 Trump escalated a public feud with [[federal-reserve|Federal Reserve]] Chair [[jerome-powell|Jerome Powell]], whom he mocked as "Mr. Too Late," and prepared for a possible firing well before Powell's term expired in May 2026.[N] After [[kevin-hassett|Kevin Hassett]] confirmed the administration was still studying removal options, the dollar index fell to a three-year low while gold set a record and [[bitcoin|Bitcoin]] spiked.[N] Badlands commentary framed the confrontation as a deliberate attempt to "provoke and disclose," arguing Trump would obtain his "preemptive cuts" while tariffs, tax breaks and onshoring created an offsetting deflationary cycle and a shift toward sound money.[N] On the same weekend Trump celebrated Easter at the White House with a sarcastic post again suggesting Joe Biden had not been the real president, the White House replaced the COVID content at covid.gov with a page on the lab-leak theory, and Trump ordered flags lowered worldwide after the death of [[pope-francis|Pope Francis]].[N] His administration also weighed invoking the [[insurrection-act|Insurrection Act of 1807]] at the southern border, threatened military action against [[iran|Iran]] over its nuclear program while signalling a deal permitting civil nuclear energy, and faced [[harvard-university|Harvard]]'s lawsuit over frozen federal research funding.[N] The Atlantic reported that his 145 percent tariffs on Chinese goods had throttled supply chains in Yiwu, the world's largest wholesale market, where factory workers responded with defiance — "You think we're afraid of America?" — and little appetite for détente.[N]"""),
("benjamin-netanyahu","entities","Badlands Commentary on the Russia-Iran Treaty (2025)","""Following [[vladimir-putin|Vladimir Putin]]'s ratification of the [[russia-iran-comprehensive-strategic-partnership-treaty|Comprehensive Strategic Partnership Agreement]] with [[iran|Iran]] in April 2025, Badlands commentary argued that Putin was "placing himself firmly between Netanyahu and Tehran, and daring Bibi to pull the trigger," noting that [[donald-trump|Trump]]'s prospective deal granting Iran a civil nuclear program appeared to be a red line no Israeli politician would accept.[N]"""),
("michael-flynn","entities","Statement on Tren de Aragua (2025)","""Amid the April 2025 federal indictments of [[tren-de-aragua|Tren de Aragua]] associates, Badlands quoted Flynn's assessment that "Tren de Aragua is a Foreign Terrorist organization directly backed by elements inside of the Venezuelan (VE) government."[N]"""),
("nayib-bukele","entities","Proposed Prisoner Swap With Venezuela (2025)","""Badlands commentary on April 21, 2025 noted that Bukele had proposed a prisoner swap with Venezuela.[N]"""),
("elon-musk","entities","Quinn Emanuel and the Harvard Lawsuit (2025)","""Coverage of [[harvard-university|Harvard University]]'s April 2025 lawsuit against the Trump administration's funding freeze noted that one of the firms Harvard retained, Quinn Emanuel, has long represented Musk, who donated $250 million to [[donald-trump|Trump]]'s campaign and became the public face of the White House [[doge|DOGE]] office and its drive to shrink the federal government.[N]"""),
]
for slug, folder, heading, body in E:
    run(slug, folder, heading, body)
