import subprocess, sys
sys.path.insert(0, "C:/Users/14053/hermes-projects/badlands-substack/scripts")
from merge774 import merge, find

LOCK = "C:/Users/14053/hermes-projects/badlands-substack/scripts/wiki_page_lock.py"

S = {}

S["donald-trump"] = """## June 2026: Lebanon rupture with Netanyahu and the Iran endgame
In a reported June 1, 2026 phone call, Trump delivered an expletive-filled rebuke to Israeli Prime Minister [[benjamin-netanyahu|Benjamin Netanyahu]], calling him "crazy," demanding "What the f*** are you doing?" and blaming [[israel|Israel]]'s actions in [[lebanon|Lebanon]] for increasing international hostility toward both Netanyahu and Israel.[[N]] According to [[axios|Axios]], Trump intervened directly to stop a planned Israeli strike on Beirut, arguing further escalation would undermine regional diplomacy and isolate Israel; Israeli officials subsequently confirmed the Beirut operation was shelved.[[N]] Trump later posted that he had held a "very productive" call with Netanyahu, that Israeli troops would not enter Beirut, that forces already en route had been turned back, and that [[hezbollah|Hezbollah]] had agreed through intermediaries to halt all shooting.[[N]]
On the negotiating track he wrote that "Iran really wants to make a deal, and it will be a good one for the USA and those that are with us," while complaining that "Dumocrats, and various seemingly unpatriotic Republicans" made his job harder by constantly "chirping" that he should move faster or slower, go to war or not go to war, and advising critics to "just sit back and relax, it will all work out well in the end - It always does!"[[N]] Badlands writer [[burning-bright|Burning Bright]] read Trump's repeated invocations of Venezuela — "the results in Iran will be amazing" and "this is being perfectly executed, on the scale of Venezuela, just a bigger, more complex operation" — as confirmation that [[iran|Iran]] was following the [[venezuela-model|Venezuela Model]] at greater scale.[[N]]
Badlands also revisited Trump's December 2021 call with [[barak-ravid|Barak Ravid]], in which he trashed Netanyahu and heavily implied Netanyahu played a role in the 2020 stolen election through his prerecorded video congratulating Biden "before the ink was even dry."[[N]] Separately, the administration was reported to be preparing to eliminate the Justice Department [[weaponization-fund|weaponization fund]], a move [[ashe-in-america|Ashe in America]] disbelieved and predicted Trump would answer by doubling the fund instead.[[N]] See [[june-2026-trump-netanyahu-lebanon-call|the June 2026 Lebanon call]] and [[iran-suspension-of-us-talks-2026|Iran's suspension of US talks]].[[N]]"""

S["benjamin-netanyahu"] = """## June 2026 Lebanon call with Trump
On June 1, 2026, President [[donald-trump|Donald Trump]] reportedly berated Netanyahu in an expletive-filled phone call, accusing him of jeopardizing US diplomatic efforts and escalating the conflict in [[lebanon|Lebanon]], calling him "crazy" and telling him "You'd be in prison if it weren't for me. I'm saving your ass. Everybody hates you now."[[N]] The confrontation followed [[iran|Iran]]'s threat to abandon negotiations with Washington over Israeli military actions in Lebanon, and Trump intervened to stop a planned Israeli strike on Beirut.[[N]] Israeli officials confirmed the Beirut operation was shelved, though Netanyahu publicly maintained that [[israel|Israel]] would continue responding to [[hezbollah|Hezbollah]] attacks and keep operations underway in southern Lebanon.[[N]] The exchange marked one of the sharpest public indications of tension between the two men since Trump's return to office.[[N]] Badlands treated it as a possible "face turn" moment and, at minimum, a shift in the [[overton-window|Overton Window]] toward an open Trump–Netanyahu divorce.[[N]] Full detail at [[june-2026-trump-netanyahu-lebanon-call|the June 2026 Trump–Netanyahu Lebanon call]].[[N]]"""

S["axios"] = """## June 2026 Lebanon call scoop
Axios reported the June 1, 2026 phone call in which President [[donald-trump|Donald Trump]] unleashed an expletive-filled rebuke of [[benjamin-netanyahu|Benjamin Netanyahu]] over escalation in [[lebanon|Lebanon]], and reported that Trump intervened to halt a planned Israeli strike on Beirut.[[N]] The outlet separately reported that the Trump administration was preparing to eliminate the Justice Department [[weaponization-fund|weaponization fund]], citing two anonymous sources — reporting [[ashe-in-america|Ashe in America]] dismissed as "statist wishful thinking" and said Trump should shame Axios for publishing.[[N]] Badlands commentary pushed back on blanket "it's Axios, it's probably fake news" dismissals, noting that [[barak-ravid|Barak Ravid]] and Mark Caputo maintain direct phone access to Trump and routinely receive exclusive information.[[N]]"""

S["barak-ravid"] = """## Access relationship with Trump
Badlands describes Ravid, along with Mark Caputo, as maintaining a direct-line relationship with President [[donald-trump|Donald Trump]], routinely conducting phone interviews in which Trump reveals exclusive information.[[N]] Ravid is characterized as the only journalist to whom Trump has openly trashed [[benjamin-netanyahu|Benjamin Netanyahu]], which he did during a December 2021 call whose audio was recorded and published in Israel but went unreported in American mainstream media.[[N]] During that call Trump also heavily implied Netanyahu played a role in the 2020 stolen election, with subtext concerning the prerecorded video Netanyahu released congratulating Biden "before the ink was even dry."[[N]]
The dynamic is described as transactional — Trump grants scoops, Ravid relays them accurately, and violating that arrangement would cost him access — while leaving open the strong possibility that Trump uses Ravid to broadcast mis- or disinformation.[[N]] Ravid's [[axios|Axios]] reporting of the June 1, 2026 call in which Trump halted a planned Israeli strike on Beirut was analyzed on those terms.[[N]] See [[june-2026-trump-netanyahu-lebanon-call|the June 2026 Trump–Netanyahu Lebanon call]].[[N]]"""

S["iran"] = """## June 2026 suspension of US talks
Iran halted indirect discussions with the United States conducted through mediators, according to [[tasnim-news-agency|Tasnim News Agency]], which cited Iranian officials linking the move to Israeli military operations in Gaza and [[lebanon|Lebanon]].[[N]] Tehran argued that Lebanon had been a key condition of a previous ceasefire arrangement and that the ceasefire had been violated, conditioning any future talks on an immediate end to Israeli operations in Gaza and Lebanon and a complete Israeli withdrawal from southern Lebanon.[[N]] Iran and allied resistance groups were reported to be weighing responses including efforts to close the [[strait-of-hormuz|Strait of Hormuz]] and activate pressure points along other waterways such as the [[bab-el-mandeb-strait|Bab el-Mandeb Strait]].[[N]] President [[donald-trump|Donald Trump]] afterward said "Iran really wants to make a deal," urging domestic critics to stop chirping and "sit back and relax."[[N]] [[burning-bright|Burning Bright]] argued the Iranian Knot follows the [[venezuela-model|Venezuela Model]], "just bigger and more complex."[[N]] See [[iran-suspension-of-us-talks-2026|Iran suspension of US talks (2026)]].[[N]]"""

S["israel"] = """## June 2026 Beirut strike halted
Israeli plans for a strike on Beirut were shelved in early June 2026 after President [[donald-trump|Donald Trump]] intervened directly with Prime Minister [[benjamin-netanyahu|Benjamin Netanyahu]], arguing that further escalation in [[lebanon|Lebanon]] would undermine regional diplomacy and isolate Israel internationally.[[N]] Trump reportedly told Netanyahu that "everybody hates Israel because of this."[[N]] Israeli officials confirmed the operation was shelved, while Netanyahu maintained that Israel would continue responding to [[hezbollah|Hezbollah]] attacks and keep military operations underway in southern Lebanon.[[N]] Israeli actions in Gaza and Lebanon were cited by [[iran|Iran]] as the reason for suspending indirect talks with Washington.[[N]]"""

S["lebanon"] = """## June 2026: Beirut strike cancelled amid Trump–Netanyahu rupture
Lebanon was the flashpoint of a reported June 1, 2026 confrontation in which President [[donald-trump|Donald Trump]] rebuked Israeli Prime Minister [[benjamin-netanyahu|Benjamin Netanyahu]] for escalating the conflict, and intervened to stop a planned Israeli strike on Beirut.[[N]] Israeli officials confirmed the Beirut operation was shelved, while Netanyahu said [[israel|Israel]] would continue responding to [[hezbollah|Hezbollah]] attacks and keep operations underway in southern Lebanon.[[N]] Trump subsequently said Israeli troops would not enter Beirut and that forces already en route had been turned back, and that Hezbollah had agreed through intermediaries to halt all shooting.[[N]] [[iran|Iran]] cited Israeli operations in Lebanon and Gaza as grounds for suspending indirect talks with Washington, demanding a complete Israeli withdrawal from areas of southern Lebanon as a condition of resuming negotiations.[[N]]"""

S["hezbollah"] = """## June 2026 de-escalation arrangement
Following President [[donald-trump|Donald Trump]]'s intervention to halt a planned Israeli strike on Beirut, Trump said Hezbollah had agreed through intermediaries to halt all shooting, with both sides committing not to attack one another as part of a de-escalation arrangement.[[N]] Prime Minister [[benjamin-netanyahu|Benjamin Netanyahu]] nonetheless maintained publicly that [[israel|Israel]] would continue responding to Hezbollah attacks and would keep military operations underway in southern [[lebanon|Lebanon]].[[N]] Hezbollah is counted among the allied resistance groups [[iran|Iran]] described as prepared to take retaliatory measures unless Israeli operations in Gaza and Lebanon ceased.[[N]]"""

S["tyler-robinson"] = """## June 2026 pretrial rulings
On June 1, 2026, Utah judge [[tony-graf|Tony Graf]] handed Robinson two pretrial defeats, ruling that his July preliminary hearing would remain open to the public and media and declining to halt the case while he appealed a separate ruling allowing cameras in the courtroom.[[N]] The July 6–10 hearing was expected to be the most substantial public presentation of evidence in the case to that point, with prosecutors planning to introduce forensic analyses, surveillance footage, witness statements, autopsy findings, and alleged messages in which Robinson admitted responsibility for the September 2025 killing of [[charlie-kirk|Charlie Kirk]] at Utah Valley University; authorities also cited DNA evidence allegedly linking him to the rifle used.[[N]] Robinson, 23, faced aggravated murder charges with prosecutors seeking the death penalty, and a separate June 12 hearing was scheduled on defense claims that prosecutors improperly influenced public opinion through media comments.[[N]] [[ashe-in-america|Ashe in America]] wrote that she doubted anyone could convince her Robinson killed Kirk, calling the story one that "never made sense."[[N]] See [[robinson-preliminary-hearing-rulings-june-2026|the June 2026 preliminary hearing rulings]].[[N]]"""

S["charlie-kirk"] = """## Prosecution of Tyler Robinson (June 2026)
Pretrial proceedings against [[tyler-robinson|Tyler Robinson]], accused of assassinating Kirk, advanced in June 2026 when Judge [[tony-graf|Tony Graf]] ruled that the July preliminary hearing would remain open to the public and media.[[N]] Prosecutors indicated they would present forensic analyses, surveillance footage, witness statements, autopsy findings, alleged admission messages, and DNA evidence tied to the rifle used in the September 2025 killing at Utah Valley University.[[N]] Prosecutors are seeking the death penalty.[[N]] [[ashe-in-america|Ashe in America]] said the case against Robinson had never made sense to her and that only an extraordinary evidentiary presentation would change her mind.[[N]]"""

S["kanye-west"] = """## Istanbul concert (June 2026)
West drew a massive crowd during a surprise late-night performance near the Bosphorus in Istanbul, described by Turkish media as one of the city's largest recent live music gatherings tied to an international artist.[[N]] The show followed a string of cancellations as European venues and festival organizers distanced themselves from him over his public remarks and online activity, and was read as evidence of his continued ability to draw large audiences outside Western European cultural institutions — and of [[turkey|Turkey]]'s growing role as a refuge for figures under reputational pressure in Europe and North America.[[N]]
[[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] framed the concert as timed with [[donald-trump|Donald Trump]]'s "face turn" against [[benjamin-netanyahu|Benjamin Netanyahu]], calling West "one of his most powerful proxies" and arguing the movement is "a cultural revolution and spiritual revival" as much as a political one.[[N]] He recalled West standing with Trump at Trump Tower before Trump first took office and asserted that West's support cost him billions, his marriage and access to his children before he "went DEFCON 3 on the Jewish elite," quoting the "Heil Hitler" lyric "I still don't get to see my children…So I became a Nazi, yeah b****, I'm the villain."[[N]] Both men, in his telling, turned heel to shift the [[overton-window|Overton Window]] and later turned babyface.[[N]] See [[kanye-west-istanbul-concert-2026|Kanye West Istanbul concert (2026)]].[[N]]"""

S["turkey"] = """## Cultural refuge role (2026)
[[kanye-west|Kanye West]]'s surprise June 2026 Istanbul performance, which drew a record-scale crowd near the Bosphorus after European venues and festivals cancelled his appearances, was cited as evidence of Turkey's growing role as an alternative destination for artists, influencers and public figures facing restrictions or reputational pressure in parts of Europe and North America.[[N]] See [[kanye-west-istanbul-concert-2026|Kanye West Istanbul concert (2026)]].[[N]]"""

S["pete-hegseth"] = """## AUKUS undersea drone announcement (June 2026)
Speaking in Singapore, War Secretary Hegseth announced that the United States, United Kingdom and Australia would jointly develop new undersea drones under the [[aukus|AUKUS]] defense pact.[[N]] He described the project as the first "Pillar Two" initiative focused on uncrewed undersea vehicles, intended to deliver "highly adaptable multi-mission UUV payloads" and maintain maritime advantage.[[N]] Hegseth said the United States remained committed to the pact — following earlier concerns over a [[pentagon|Pentagon]] review that eased when President [[donald-trump|Donald Trump]] reaffirmed support — and was moving quickly to expand submarine capabilities in the Pacific.[[N]] See [[aukus-undersea-drone-program|AUKUS undersea drone program]].[[N]]"""

S["pentagon"] = """## AUKUS review and reversal (2026)
Earlier Pentagon review of the [[aukus|AUKUS]] pact generated concern among partner governments, which eased after President [[donald-trump|Donald Trump]] reaffirmed US support; War Secretary [[pete-hegseth|Pete Hegseth]] said in June 2026 that Washington remained committed and was moving quickly to expand submarine capabilities in the Pacific.[[N]] See [[aukus-undersea-drone-program|AUKUS undersea drone program]].[[N]]"""

S["strait-of-hormuz"] = """## June 2026 closure threat
After [[iran|Iran]] suspended indirect talks with the United States, [[tasnim-news-agency|Tasnim News Agency]] reported that Tehran and allied resistance groups were weighing efforts to close the Strait of Hormuz and to activate pressure points along other strategic waterways, including the [[bab-el-mandeb-strait|Bab el-Mandeb Strait]], unless Israeli operations in Gaza and [[lebanon|Lebanon]] ended.[[N]]"""

S["mark-levin"] = """## Reaction to the June 2026 Netanyahu call leak
Following [[axios|Axios]]'s report of President [[donald-trump|Donald Trump]]'s expletive-filled June 1, 2026 call with [[benjamin-netanyahu|Benjamin Netanyahu]], Levin called for an FBI investigation to identify the leaker.[[N]] [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] read that reaction — alongside [[laura-loomer|Laura Loomer]]'s complaints about disloyalty in Trump's camp — as circumstantial evidence the call was real, arguing that if it had not happened they would simply have brushed the story off as fake news rather than demanding "heads on pikes."[[N]]"""

S["laura-loomer"] = """## Reaction to the June 2026 Netanyahu call leak
Loomer publicly denounced disloyalty within [[donald-trump|Donald Trump]]'s camp after [[axios|Axios]] reported his expletive-filled June 1, 2026 phone call with [[benjamin-netanyahu|Benjamin Netanyahu]].[[N]] Badlands writer [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] cited her response, along with [[mark-levin|Mark Levin]]'s call for an FBI leak investigation, as evidence that the call likely occurred and that its participants feared an audio recording existed.[[N]]"""

S["ashe-in-america"] = """## June 2026 commentary
Ashe in America rejected [[axios|Axios]]'s report that the Trump administration would scrap the Justice Department [[weaponization-fund|weaponization fund]], dismissing the two-anonymous-source story as "statist wishful thinking" and predicting that maneuvers by figures such as Senator [[michael-bennet|Michael Bennet]] and Governor [[gavin-newsom|Gavin Newsom]] — who were floating taxing weaponization disbursements at 100 percent to deny recipients like [[tina-peters|Tina Peters]] — would push President [[donald-trump|Donald Trump]] to double the fund and mock them instead.[[N]] Writing as a Coloradan, she quipped an apology to America for Bennet, and insisted "there must be accountability."[[N]]
On the [[charlie-kirk|Charlie Kirk]] case, she noted that [[tyler-robinson|Tyler Robinson]]'s July hearing would follow the nation's birthday and present the most extensive evidence yet, but said the story "never made sense" and that the institutional establishment's shaming of question-askers is the signature of "a tightly controlled lie."[[N]] She said she would probably still watch, while doubting any presentation could convince her Robinson killed Kirk.[[N]]"""

S["ghostofbasedpatrickhenry"] = """## June 2026 analysis
GhostofBasedPatrickHenry treated the reported June 1, 2026 Trump–Netanyahu phone call as a possible inflection point in the long-anticipated Trump "face turn" against [[benjamin-netanyahu|Benjamin Netanyahu]], while cautioning that a single reported event proves little after "too many rugpulls."[[N]] He defended the credibility of [[axios|Axios]]'s [[barak-ravid|Barak Ravid]] as a journalist with a unique access relationship to [[donald-trump|Donald Trump]], noted Ravid's December 2021 call in which Trump trashed Netanyahu and implied his role in the 2020 stolen election, and argued that reactions from "Mossad Media" — [[mark-levin|Mark Levin]] demanding an FBI leak probe, [[laura-loomer|Laura Loomer]] decrying disloyalty — suggested the call was real.[[N]] Regardless of its truth, he argued, the narrative advanced the [[overton-window|Overton Window]] toward an ugly Trump–Netanyahu divorce with [[israel|Israel]] waging war "in a fit of blind rage without the support of the US."[[N]]
He also framed [[kanye-west|Kanye West]]'s Istanbul concert as a parallel cultural signal, arguing that West and Trump followed the same heel-turn-then-face-turn trajectory and that the struggle is "a cultural revolution and spiritual revival" as much as a political movement.[[N]]"""

S["burning-bright"] = """## The Iranian Knot and the Venezuela template (June 2026)
Burning Bright argued that [[donald-trump|Donald Trump]] treats the Iran conflict as an accelerant into the [[global-golden-age|Golden Age]] rather than a threat to his mandate, and that understanding this requires inverting the assumed endgame of his plans "not just for the United States, but for a reimagined world."[[N]] He pointed to Trump's own statements — "just like the results in Venezuela… the results in Iran will be amazing" and "this is being perfectly executed, on the scale of Venezuela, just a bigger, more complex operation" — as evidence that the Iranian Knot follows the [[venezuela-model|Venezuela Model]].[[N]] Quoting his January 11 essay "Sovereign Disentanglement," he asked whether Trump would "spirit away Khamenei, only to leave the rest of his ruling party in control while rug-pulling the global regime's planned version of the change event."[[N]] The longer the process runs, he argued, the more impossible it becomes for the enemy to undo the damage to their system, which is why the [[collectorate|Collectorate]] is panicking: they know the [[iran-war|Iran War]]'s resolution will bring a new vision for geopolitics, global governance, finance and trade — the [[sovereign-alliance|Sovereign Alliance]] and the [[multipolar-war|Multipolar War]], or what he calls the Trump Transition.[[N]]"""

S["venezuela-model"] = """## Application to Iran (2026)
[[burning-bright|Burning Bright]] argued in June 2026 that the Iranian confrontation is the Venezuela Model applied at larger scale, citing [[donald-trump|Donald Trump]]'s own comparisons: "just like the results in Venezuela… the results in Iran will be amazing," and "this is being perfectly executed, on the scale of Venezuela, just a bigger, more complex operation."[[N]] Because the template is understood, he claimed, the process in [[iran|Iran]] "can be mapped in detail" rather than merely cheered from the sidelines or glimpsed on the macro in the Q Drops.[[N]]"""

S["truth-social"] = """## June 2026 Lebanon and Iran posts
President [[donald-trump|Donald Trump]] used Truth Social to announce that he had held a "very productive" call with [[benjamin-netanyahu|Benjamin Netanyahu]], that Israeli troops would not enter Beirut, that forces already en route had been turned back, and that [[hezbollah|Hezbollah]] had agreed through intermediaries to halt all shooting.[[N]] In the same post he wrote that "Iran really wants to make a deal," criticized "Dumocrats, and various seemingly unpatriotic Republicans" for constant "chirping" that made negotiation harder, and told critics to "just sit back and relax, it will all work out well in the end - It always does!"[[N]]"""

S["aukus"] = """## Undersea drone program (June 2026)
War Secretary [[pete-hegseth|Pete Hegseth]] announced in Singapore that the United States, United Kingdom and Australia would jointly develop new undersea drones under the pact — the first "Pillar Two" initiative focused on uncrewed undersea vehicles, aimed at delivering "highly adaptable multi-mission UUV payloads" to maintain maritime advantage.[[N]] See [[aukus-undersea-drone-program|AUKUS undersea drone program]].[[N]]"""

S["weaponization-fund"] = """## Related developments
The reported shutdown of the fund coincided with the same week's reported rupture between President [[donald-trump|Donald Trump]] and [[benjamin-netanyahu|Benjamin Netanyahu]] over [[lebanon|Lebanon]], both stories sourced to [[axios|Axios]] and treated by Badlands as narrative deployments to be assessed for intent as much as accuracy.[[N]] The fund's remit had covered investigations into alleged misconduct involving federal law enforcement, intelligence agencies, censorship coordination, and politically motivated prosecutions, and Ashe in America characterized its purpose as restitution while insisting accountability remained outstanding.[[N]]"""

S["michael-bennet"] = """## Weaponization disbursement tax proposal (2026)
Bennet was named by [[ashe-in-america|Ashe in America]] among leftist politicians discussing taxing [[weaponization-fund|weaponization fund]] disbursements at 100 percent, a measure she framed as an attempt to ensure recipients such as [[tina-peters|Tina Peters]] could not benefit.[[N]] She predicted such moves would prompt President [[donald-trump|Donald Trump]] to double the fund and mock its opponents, and, writing as a Coloradan, offered a sardonic apology to America for Bennet.[[N]]"""

S["gavin-newsom"] = """## Weaponization fund tax strategy (2026)
[[ashe-in-america|Ashe in America]] identified Newsom as pursuing a strategy similar to Senator [[michael-bennet|Michael Bennet]]'s regarding the Justice Department [[weaponization-fund|weaponization fund]] — proposals to tax weaponization disbursements at 100 percent so that recipients such as [[tina-peters|Tina Peters]] could not benefit from them.[[N]]"""

S["tina-peters"] = """## Weaponization disbursements (2026)
Peters was cited by [[ashe-in-america|Ashe in America]] as the archetypal intended beneficiary of the Justice Department [[weaponization-fund|weaponization fund]], whose disbursements leftist politicians including Senator [[michael-bennet|Michael Bennet]] and Governor [[gavin-newsom|Gavin Newsom]] were reportedly proposing to tax at 100 percent specifically to deny such recipients any benefit.[[N]]"""

S["tony-graf"] = """## Openness rulings and expected evidence
Graf's June 1, 2026 rulings kept the July 6–10 preliminary hearing open to the public and media and declined to pause the case pending appeal of a separate order allowing cameras in the courtroom.[[N]] The hearing was expected to be the most substantial public presentation of evidence in the case, with prosecutors planning forensic analyses, surveillance footage, witness statements, autopsy findings, alleged admission messages and DNA evidence tied to the rifle.[[N]] A separate June 12 hearing was set on defense claims that prosecutors improperly influenced public opinion through media comments.[[N]] See [[robinson-preliminary-hearing-rulings-june-2026|Robinson preliminary hearing rulings (June 2026)]].[[N]]"""

S["department-of-justice"] = """## Reported end of the weaponization fund (2026)
The Trump administration was reported in June 2026 to be preparing to eliminate a Justice Department initiative known internally as the [[weaponization-fund|weaponization fund]], established to support investigations and legal actions tied to alleged political abuse by federal agencies during prior administrations.[[N]] Officials reportedly viewed the effort as politically burdensome and legally difficult to sustain as attention shifted to broader institutional reforms and budget priorities, with critics arguing it had created expectations of sweeping criminal accountability that proved hard to deliver in court.[[N]] The reported move came amid wider restructuring across the department and renewed debate in Trump-aligned circles over whether systemic reform or high-profile prosecutorial action should be the primary strategy.[[N]]"""

S["badlands-blitz"] = """## Episode 19
Episode 19 featured [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] and [[burning-bright|Burning Bright]] stepping back from direct analysis of events in [[iran|Iran]] to examine the grand strategy at play between [[donald-trump|Donald Trump]] and his "Frenemies."[[N]]"""

S["iran-war"] = """## June 2026: talks suspended, Beirut strike halted
[[iran|Iran]] suspended indirect talks with the United States over Israeli operations in Gaza and [[lebanon|Lebanon]], threatening to close the [[strait-of-hormuz|Strait of Hormuz]] and pressure other waterways including the [[bab-el-mandeb-strait|Bab el-Mandeb Strait]].[[N]] Days later President [[donald-trump|Donald Trump]] halted a planned Israeli strike on Beirut and announced a Hezbollah shooting halt, saying "Iran really wants to make a deal."[[N]] [[burning-bright|Burning Bright]] argued the war is a story whose resolution will bring a new vision for geopolitics, global governance, finance and trade, and that the [[collectorate|Collectorate]] is panicking precisely because it understands that endgame.[[N]]"""

S["global-golden-age"] = """## Iran as accelerant (2026)
[[burning-bright|Burning Bright]] argued in June 2026 that [[donald-trump|Donald Trump]] treats the Iran conflict — the very confrontation said to be eroding his public mandate — as "the very accelerant into the Golden Age he built his public platform on a decade ago," a plan aimed not only at the United States but at "a reimagined world."[[N]]"""

S["sovereign-alliance"] = """## Iran and the multipolar thesis (2026)
[[burning-bright|Burning Bright]] wrote that the questions raised in his January 2026 essay "Sovereign Disentanglement" — including whether [[donald-trump|Donald Trump]] would remove Khamenei while leaving the rest of the ruling party in place, rug-pulling the global regime's own planned change event — "cemented my belief in the Sovereign Alliance and the [[multipolar-war|Multipolar War]]."[[N]] He argued the longer the process plays out in [[iran|Iran]], the more impossible it becomes for the adversary to undo the damage to its system.[[N]]"""

S["badlands-media"] = """## Great American Restoration Tour 12
The June 2026 Brief promoted in-person and virtual tickets to GART 12 in Deadwood, describing the quarterly three-day event as a "patriot-packed" gathering with Badlands hosts and community members.[[N]]"""

ok, fail = [], []
for slug, section in S.items():
    try:
        p = find(slug)
    except SystemExit as e:
        fail.append(str(e)); continue
    if "raw/badlands-brief-774.md" in p.read_text(encoding="utf-8"):
        ok.append(slug + "(already)"); continue
    r = subprocess.run([sys.executable, LOCK, "acquire", slug], capture_output=True, text=True)
    if r.returncode != 0:
        fail.append(f"LOCKFAIL {slug}"); continue
    try:
        merge(slug, section)
        ok.append(slug)
    except SystemExit as e:
        fail.append(f"{slug}: {e}")
    finally:
        subprocess.run([sys.executable, LOCK, "release", slug], capture_output=True, text=True)

print("OKCOUNT", len(ok))
print("FAIL", fail)
