# -*- coding: utf-8 -*-
import sys, io
sys.path.insert(0,'scripts')
from merge_051 import merge as _merge
ONLY=set(sys.argv[1:])
def merge(path,*a):
    slug=path.split('/')[-1][:-3]
    if ONLY and slug not in ONLY:
        return
    _merge(path,*a)
W='wiki/'
merge(W+'entities/donald-trump.md','November 2023 NBC News poll',
 u"An NBC News national poll released on November 19, 2023 showed Trump leading President Joe Biden for the first time in a hypothetical 2024 general-election matchup, though the margin fell within the poll's margin of error for a contest still more than eleven months away.[n] The shift accompanied a decline in Biden's approval to 40 percent, driven heavily by disapproval of his handling of foreign policy and the Israel-Hamas war.[n]")
merge(W+'entities/joe-biden.md','November 2023 approval collapse',
 u"An NBC News poll released on November 19, 2023 put Biden's approval rating at 40 percent, the lowest level of his presidency, with strong majorities of all voters disapproving of his handling of foreign policy and of the Israel-Hamas war.[n] For the first time in that survey series he trailed former President Donald Trump in a hypothetical general-election matchup, albeit within the margin of error.[n] Erosion was sharpest among Democrats, a majority of whom said Israel had gone too far in its military action in Gaza, and among voters aged 18 to 34, of whom 70 percent disapproved of his handling of the war.[n] Democratic pollster Jeff Horwitt of Hart Research Associates said Biden was \"at a uniquely low point in his presidency,\" attributing much of it to how Americans viewed his foreign policy actions, while Republican pollster Bill McInturff of Public Opinion Strategies said he could not recall another time when foreign affairs not involving US troops had so transformed the American political landscape.[n]\n\nDuring the same period Biden's administration pressed Congress for supplemental funding split between Ukraine and Israel, while Defense Secretary Lloyd Austin and CIA Director William Burns made separate unannounced trips to Ukraine as the counteroffensive faltered.[n] Badlands Media commentary framed the Ukraine collapse as dragging the CIA and the Biden administration down with it in the wider information war.[n] Biden's characterization of Chinese President Xi Jinping as a \"dictator\" at the close of their San Francisco meeting also soured the visit, after which Xi publicly celebrated \"firm\" ties with Russia.[n]")
merge(W+'entities/haaretz.md','Nova music festival friendly-fire report (2023)',
 u"On November 18, 2023, Haaretz reported that an Israeli police investigation into the October 7 Hamas attack on the Nova music festival near the Gaza border had found that an Israeli attack helicopter fired on some of the festival attendees.[n] According to a police source cited in the report, the combat helicopter arrived from the Ramat David base and fired at Hamas fighters and other Palestinians who had crossed the border fence, but also hit Israelis at the festival; police put the total killed at the site at 364.[n] The report marked the first official acknowledgement that Israeli forces killed some of their own at the festival, after the military and rescue services had said 260 Israelis were killed there in a deliberate massacre by Hamas and Palestinians.[n]")
merge(W+'entities/the-epoch-times.md','November 2023 reporting cited by Badlands',
 u"The Epoch Times supplied three items republished in the November 21, 2023 Badlands News Brief: a report on the highest-ever US childhood vaccine exemption rate drawn from a November 10 CDC publication; coverage of Michigan's civil-rights charge against salon owner Christine Geiger and Studio 8 Hair Lab; and a feature on psychiatrists describing \"transhausen by proxy,\" a coined term for narcissistic parents pushing gender transition on their children.[n]")
merge(W+'entities/zerohedge.md','November 2023 reporting cited by Badlands',
 u"ZeroHedge supplied several items republished in the November 21, 2023 Badlands News Brief, including coverage of X Corp's lawsuit against Media Matters and the accompanying Texas attorney general investigation, the separate unannounced Ukraine trips by Defense Secretary Lloyd Austin and CIA Director William Burns, and Xi Jinping's celebration of \"firm\" China-Russia ties after his San Francisco visit.[n]")
merge(W+'entities/badlands-media.md','November 21, 2023 News Brief',
 u"The November 21, 2023 edition of the Badlands News Brief, headlined \"Lawsuits Can Be Very Effective ...\", covered the X Corp suit against Media Matters, the record US childhood vaccine exemption rate, the November 2023 NBC News poll showing Biden at 40 percent approval, Michigan's discrimination charge against a salon owner, and the urgent US visits to Ukraine by Lloyd Austin and William Burns, with bonus items on the Nova music festival friendly-fire admission, \"transhausen by proxy,\" and Xi Jinping's affirmation of ties with Russia.[n] Commentary was contributed by Burning Bright and Ashe in America.[n]")
merge(W+'concepts/lawfare.md','Michigan salon case and the Jack Phillips precedent (2023)',
 u"Commenting on Michigan's civil-rights charge against salon owner Christine Geiger, Ashe in America argued that the point of such actions was not client safety but ensuring that a proprietor is \"not allowed to not play the pronoun game.\"[n] She pointed to Colorado baker Jack Phillips, who had by then spent more than eleven years in court over refusing to bake a same-sex wedding cake, won at the Supreme Court, and then faced a fresh case over a gender-transition cake, as the instructive test kitchen for the practice.[n] She described lawfare as having two aims — punishing opponents, and chiseling away at the contours of the law so that each case becomes a building block toward a new precedent — with the process itself serving as the punishment while the regime fundraises and saturates the narrative and the defendant struggles to find counsel.[n] She called for the practice to be abolished and for harsher penalties for weaponizing the law out of frivolity, warning that otherwise it becomes normal.[n]\n\nBurning Bright, writing on the X Corp suit against Media Matters and the parallel Texas attorney general investigation, framed the same period as a \"lawsuit cascade\" in the information war and as the beginning of a template-setting campaign against those who had assaulted constitutional free-speech rights, fought simultaneously in court and in the court of public opinion ahead of the 2024 election.[n]")
merge(W+'entities/burning-bright.md','November 2023 commentary',
 u"In the November 21, 2023 Badlands News Brief, Burning Bright wrote on three items.[n] On X Corp's suit against Media Matters he described a developing \"lawsuit cascade\" in the information war, called Elon Musk an enigmatic figure among Anons who was nonetheless standing in the breach against the Deep State's narrative power-projection arm, and predicted the suits were the start of a template-setting, scorched-earth campaign over free speech waged both in court and in the court of public opinion ahead of the 2024 election.[n] On the NBC News poll showing Biden at 40 percent approval he argued that mainstream polls are useful for reading Establishment Uniparty narrative intentions and internal consistency within the Collective Mind, and that the poll was damning less because a Democrat-tailored sample chose Trump than because of why it did so — the Israel-Gaza chaos creating \"shatterpoints\" that push the Collective Mind toward truth, with trauma once used to control Americans now freeing them.[n] On the Austin and Burns trips to Kiev he said the Ukraine proxy war's kinetic and narrative collapse had exposed proxy presidents and proxy wars to an awakening public and was dragging the CIA and the Biden administration down with it.[n]")
merge(W+'entities/ashe-in-america.md','November 2023 commentary',
 u"In the November 21, 2023 Badlands News Brief, Ashe in America wrote on the CDC report showing the highest-ever US childhood vaccine exemption rate, describing a close friend with seven children, three of whom she said were vaccine-injured around the turn of the century, and saying she stopped vaccinating her own children entirely during the HPV push when her sons became teenagers.[n] She argued that the awakening to government corruption is inseparable from scrutiny of vaccines, that with more than two thirds of Americans awake to widespread corruption they were necessarily examining vaccines more critically, and that the issue reduces to institutional trust that has been repeatedly forfeited.[n]\n\nOn Michigan's discrimination charge against salon owner Christine Geiger, she argued the salon was simply signalling it was not a good fit for clients who require a safe space, and that the regime's real goal was to forbid opting out of the pronoun question.[n] She used Jack Phillips's eleven-year litigation history in Colorado to illustrate lawfare's twin aims of punishing opponents and reshaping legal precedent, warning that if a court can punish a salon for not playing the pronoun game the outlook is poor, since \"we only have rights if we can exercise them.\"[n]")
