# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, r'C:/Users/14053/hermes-projects/badlands-substack/scripts')
from merge_f6e import run

U = []
def a(slug, title, body):
    U.append((slug, '## %s\n\n%s' % (title, body)))

a('donald-trump', 'Epstein files bill, Saudi diplomacy, and Mamdani meeting (November 2025)',
 'On Wednesday, November 19, 2025, President Trump signed legislation ordering the [[department-of-justice|Justice Department]] to release documents from its long-running investigation into sex offender [[jeffrey-epstein|Jeffrey Epstein]], files sought by both his political opponents and members of his own base who had pressed for greater transparency.[{N}] The material could shed more light on Epstein\'s activities; Epstein socialized with Trump and other notable figures before his 2008 conviction for soliciting a minor for prostitution.[{N}] Reuters described the scandal as a thorn in Trump\'s side for months, partly because he had amplified conspiracy theories about Epstein to his own supporters, many of whom believe his administration covered up Epstein\'s ties to powerful figures.[{N}]\n\n'
 'The same week Trump hosted Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]] for a black-tie White House dinner and an Oval Office meeting, followed by the [[saudi-us-investment-forum|US-Saudi Investment Forum]] at the Kennedy Center, where Trump said $270 billion of Saudi investment had already been negotiated and locked in as the first portion of a promised $1 trillion.[{N}] At the forum Trump said the crown prince had asked him to help end the war in [[sudan|Sudan]]: "His majesty would like me to do something very powerful having to do with Sudan... it was not on my charts to be involved in... But I just see how important that is to you... And we\'re going to start working on Sudan."[{N}] He later condemned the "tremendous atrocities" in Sudan\'s civil war and said he would work with Saudi Arabia, the United Arab Emirates and Egypt to end it.[{N}]\n\n'
 'Trump also announced on Truth Social that he had agreed to meet New York City Mayor-elect [[zohran-mamdani|Zohran Mamdani]] in the Oval Office on Friday, November 21, writing: "Communist Mayor of New York City, Zohran \'Kwame\' Mamdani, has asked for a meeting."[{N}] Trump had urged New York voters to back Mamdani\'s opponent, former Governor Andrew Cuomo, and had repeatedly attacked Mamdani in public statements.[{N}] Separately, Rep. [[eugene-vindman|Eugene Vindman]] demanded Trump release the transcript of a call with the Saudi crown prince held after the killing of [[jamal-khashoggi|Jamal Khashoggi]].[{N}]')

a('pam-bondi', 'Epstein Files Transparency Act and redaction authority (November 2025)',
 'After the House and Senate voted on Tuesday, November 18, 2025 to require public release of the government\'s Epstein files, scrutiny turned to a provision of the [[epstein-files-transparency-act|Epstein Files Transparency Act]] that could allow Attorney General Bondi to redact certain details.[{N}] The bill requires Bondi to release all files — including internal communications and investigative materials — related to [[jeffrey-epstein|Jeffrey Epstein]] and his co-conspirator [[ghislaine-maxwell|Ghislaine Maxwell]] within 30 days of enactment, but permits redaction in specific instances, including documents that "would jeopardize an active federal investigation or ongoing prosecution."[{N}] Bondi said the Justice Department would release the files within 30 days.[{N}] Badlands contributor [[jon-herold|Jon Herold]] commented drily that "the files are back on Bondi\'s desk, and surely this review will net different results."[{N}]')

a('epstein-files-transparency-act', 'Signature and redaction controversy (November 2025)',
 'The Epstein Files Transparency Act cleared both the House and the Senate on Tuesday, November 18, 2025, and was signed by President [[donald-trump|Donald Trump]] the following day, ordering the [[department-of-justice|Justice Department]] to release documents from its long-running investigation into [[jeffrey-epstein|Jeffrey Epstein]].[{N}] The law requires Attorney General [[pam-bondi|Pam Bondi]] to release all files, including internal communications and investigative materials, relating to Epstein and his co-conspirator [[ghislaine-maxwell|Ghislaine Maxwell]] within 30 days of enactment.[{N}] A provision permitting redaction of records in specific instances — including material that "would jeopardize an active federal investigation or ongoing prosecution" — drew immediate scrutiny as a potential loophole allowing the attorney general to withhold details.[{N}]')

a('jeffrey-epstein', 'Files release legislation (November 2025)',
 'On November 19, 2025, President [[donald-trump|Donald Trump]] signed legislation ordering the [[department-of-justice|Justice Department]] to release documents from its long-running investigation into Epstein.[{N}] Reuters noted that the material could shed more light on the activities of Epstein, who socialized with Trump and other notable figures before his 2008 conviction on charges of soliciting a minor for prostitution, and that many Trump voters believe his administration covered up Epstein\'s ties to powerful figures and obscured details surrounding his death — ruled a suicide — in a Manhattan jail in 2019 as he faced federal sex trafficking charges.[{N}] The [[epstein-files-transparency-act|Epstein Files Transparency Act]] requires release of all files relating to Epstein and [[ghislaine-maxwell|Ghislaine Maxwell]] within 30 days, subject to redaction authority vested in Attorney General [[pam-bondi|Pam Bondi]].[{N}]')

a('ghislaine-maxwell', 'Coverage under the Epstein Files Transparency Act (November 2025)',
 'The [[epstein-files-transparency-act|Epstein Files Transparency Act]], passed by both chambers of Congress in November 2025 and signed by President [[donald-trump|Donald Trump]] on November 19, expressly requires Attorney General [[pam-bondi|Pam Bondi]] to release all files — including internal communications and investigative materials — related to [[jeffrey-epstein|Jeffrey Epstein]] and his co-conspirator Maxwell within 30 days of enactment.[{N}] The statute\'s redaction provision, which permits withholding records that would jeopardize an active federal investigation or ongoing prosecution, drew scrutiny as a possible limit on what would ultimately be disclosed about Maxwell.[{N}]')

a('mohammed-bin-salman', 'Washington visit, Sudan request, and investment forum (November 2025)',
 'During a November 2025 visit to the United States, Crown Prince Mohammed bin Salman asked President [[donald-trump|Donald Trump]] to help end the war in [[sudan|Sudan]]; Trump told the [[saudi-us-investment-forum|US-Saudi Investment Forum]] that "his majesty would like me to do something very powerful having to do with Sudan" and pledged to start working on the conflict with Saudi Arabia, the United Arab Emirates and Egypt.[{N}] The visit included an Oval Office meeting and a black-tie dinner at the [[white-house|White House]] on Tuesday, November 18, honoring the crown prince, who had previously been labeled a "pariah" over his role in the 2018 killing of Washington Post opinion columnist [[jamal-khashoggi|Jamal Khashoggi]].[{N}] Many tech and Wall Street executives who had distanced themselves from the kingdom seven years earlier attended, signaling openness to business with Saudi Arabia.[{N}]\n\n'
 'The economic momentum shifted the next day to the investment forum at the Kennedy Center, where government-level agreements were translated into private-sector deals worth billions; Trump said $270 billion of Saudi investment had been locked in as the first tranche of a promised $1 trillion.[{N}] Rep. [[eugene-vindman|Eugene Vindman]] separately demanded release of the transcript of a Trump call with the crown prince held after the Khashoggi assassination, calling it one of the two most problematic calls he reviewed while at the National Security Council.[{N}]')

a('jamal-khashoggi', 'Legacy in the 2025 MBS Washington visit',
 'The 2018 killing of Khashoggi, a Washington Post opinion columnist and Virginia resident who was dismembered in the Saudi Consulate in Turkey in a killing US intelligence officials concluded Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]] had ordered, resurfaced during the crown prince\'s November 2025 visit to Washington.[{N}] Rep. [[eugene-vindman|Eugene Vindman]] called on President [[donald-trump|Donald Trump]] to release the transcript of a phone call with the crown prince that took place in the aftermath of the assassination, saying the call "was about the murder of an American resident — a Virginia resident — and a Washington Post reporter."[{N}] The Washington Post noted that many tech and Wall Street executives who had shunned the kingdom after the killing attended the November 18 [[white-house|White House]] dinner in the crown prince\'s honor.[{N}]')

a('white-house', 'Dinner for Mohammed bin Salman (November 2025)',
 'On Tuesday, November 18, 2025, the White House hosted a black-tie dinner in the East Room in honor of Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]], attended by the president\'s eldest son, the world\'s richest man, and dozens of prominent tech, media and sports figures.[{N}] Tech billionaire [[elon-musk|Elon Musk]] made his first public appearance at the White House since his feud with the president earlier that year.[{N}] The gathering marked a reversal for executives who had distanced themselves from the kingdom after the 2018 killing of [[jamal-khashoggi|Jamal Khashoggi]], with leaders of America\'s biggest companies signaling they were open for business with Saudi Arabia.[{N}] Badlands contributor [[burning-bright|Burning Bright]] read the optics of Musk as a guest of honor as evidence that [[kayfabe|kayfabe]] is "the premier narrative weapon of choice" for President [[donald-trump|Donald Trump]], arguing that "Trump and Elon signal GROWTH."[{N}]')

a('elon-musk', 'White House dinner and humanoid robot claims (November 2025)',
 'Musk made his first public appearance at the [[white-house|White House]] since his feud with President [[donald-trump|Donald Trump]] earlier in 2025 at the November 18 black-tie dinner honoring Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]].[{N}] His businesses are increasingly courting deals in Saudi Arabia: [[tesla|Tesla]] began selling vehicles in the market earlier that year, and [[xai|xAI]], maker of the chatbot Grok, has reportedly held talks about data center deals with the kingdom-backed artificial intelligence company Humain.[{N}]\n\n'
 'Speaking at the [[saudi-us-investment-forum|US-Saudi Investment Forum]], Musk claimed AI humanoid robots will "eliminate poverty" and "make everyone wealthy," said Tesla would not be the only company making them but would pioneer the technology, and predicted that advances in AI and robotics would make work "optional."[{N}] Badlands contributor [[chris-paul|Chris Paul]] responded sardonically — "Wait... they\'re only promising to solve absolute poverty and they\'ve already solved it?" — and offered "three cheers for Wizzard Elon and the Machine."[{N}] Contributor [[burning-bright|Burning Bright]] read Musk\'s appearance alongside Trump as a deliberate signal of growth.[{N}]')

a('tesla', 'Saudi market entry and humanoid robots (2025)',
 'Tesla began selling vehicles in Saudi Arabia in 2025 as [[elon-musk|Elon Musk]]\'s businesses increasingly courted deals in the kingdom.[{N}] At the November 2025 [[saudi-us-investment-forum|US-Saudi Investment Forum]], Musk said Tesla would not be the only company to make AI humanoid robots but would pioneer the technology, claiming such robots would "eliminate poverty" and make work "optional."[{N}]')

a('xai', 'Reported Saudi data center talks (2025)',
 'xAI, [[elon-musk|Elon Musk]]\'s artificial intelligence company and maker of the chatbot Grok, has reportedly held talks about data center deals with Humain, the artificial intelligence company backed by the Saudi kingdom, amid a broader push by Musk\'s businesses into the Saudi market in 2025.[{N}]')

a('saudi-us-investment-forum', 'November 2025 Washington forum',
 'The economic momentum generated by the November 18, 2025 [[white-house|White House]] meeting between Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]] and President [[donald-trump|Donald Trump]] shifted the following day to the US-Saudi Investment Forum at the Kennedy Center in Washington, D.C.[{N}] Hosted by the Ministry of Investment of Saudi Arabia under the theme "Leadership for Growth: Strengthening the Saudi-US Economic Partnership," the forum brought together senior government officials, investors and CEOs from some of America\'s most powerful firms, and rapidly translated the government-level agreements announced in the Oval Office and at the previous evening\'s gala dinner into concrete private-sector deals worth billions.[{N}]\n\n'
 'Trump announced at the forum that $270 billion of Saudi investment had already been successfully negotiated and locked in for the US economy, representing the first portion of the $1 trillion the crown prince had promised to procure.[{N}] It was also at this forum that Trump said he would begin "working" on the war in [[sudan|Sudan]] at the crown prince\'s request, and that [[elon-musk|Elon Musk]] made his claim that humanoid robots would eliminate poverty.[{N}] Badlands contributor [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] noted that the same organization had hosted the event where Trump spoke in Riyadh on May 13, 2025, and predicted more deals would be announced in the following weeks.[{N}]')

a('sudan', 'Trump pledge of involvement and the naval base thesis (November 2025)',
 'On November 19, 2025, President [[donald-trump|Donald Trump]] said he would start "working" on the war in Sudan after Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]] asked him to help end the conflict during a visit to the United States.[{N}] Since its outbreak in April 2023, the war between [[sudanese-armed-forces|Sudan\'s army]] and the paramilitary [[rapid-support-forces|Rapid Support Forces]] has killed tens of thousands of people and displaced nearly 12 million; Trump condemned the "tremendous atrocities" and said he would work with Saudi Arabia, the United Arab Emirates and Egypt to end the conflict.[{N}]\n\n'
 'Badlands contributor [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] tied the request to Russian involvement, restating a theory advanced since 2023 that the civil war began because the Sudanese government — against the wishes of the Biden administration and the [[state-department|State Department]] — approved plans for construction of a [[russian-naval-base-in-sudan|Russian naval base]] at Sudan\'s main port, which would be Russia\'s first formal military installation on African soil.[{N}] The United States closed its embassy in Sudan in 1996 and ended diplomacy with its government until Joe Biden restarted the mission in early 2022; ambassador [[john-godfrey|John Godfrey]] arrived in August 2022 and, per the commentary, immediately threatened sanctions if Sudan accepted Russia\'s proposal.[{N}] Sudan announced acceptance in February 2023 and civil war broke out roughly two months later, after which Godfrey and his staff were evacuated.[{N}]')

a('russian-naval-base-in-sudan', 'Badlands civil war thesis and 2025 finalization',
 'Badlands commentary published in November 2025 advanced the theory that Sudan\'s civil war began because the Sudanese government, against the wishes of the Biden administration and the [[state-department|State Department]], approved plans for the construction of a Russian naval base at Sudan\'s main port — which would be Russia\'s first formal military installation ever established on African soil.[{N}] Under this account, Biden restarted the US diplomatic mission in Khartoum in early 2022 as Sudan neared the end of its multi-year review of Vladimir Putin\'s proposal, and ambassador [[john-godfrey|John Godfrey]] arrived in August 2022 and threatened sanctions if the proposal were accepted.[{N}] Sudan announced acceptance in February 2023; war broke out about two months later and the embassy was evacuated, an outcome the commentary called "a tentative success" for a mission of destabilization and explicitly characterized as a color revolution operation.[{N}] Russia and Sudan announced in 2025 that all details of the agreement had been finalized and that construction would begin as soon as possible.[{N}]')

a('state-department', 'Sudan color revolution allegation',
 'Badlands commentary in November 2025 accused the State Department of engineering the destabilization of [[sudan|Sudan]] to prevent construction of a [[russian-naval-base-in-sudan|Russian naval base]] at the country\'s main port.[{N}] The account notes the US closed its embassy in Sudan in 1996 and ended diplomacy with its government until Joe Biden restarted the mission in early 2022, dispatching [[senior-executive-service|Senior Executive Service]] official [[john-godfrey|John Godfrey]] as ambassador; Godfrey arrived in August 2022 after Senate confirmation and, per the commentary, immediately threatened the Sudanese government with sanctions if it accepted Russia\'s proposal.[{N}] Contributor [[ghostofbasedpatrickhenry|GhostofBasedPatrickHenry]] answered his own question — whether he was accusing Godfrey of spearheading a color revolution (regime change) operation — with "Yes. Yes, I am."[{N}]')

a('senior-executive-service', 'Sudan ambassadorship example',
 'Badlands commentary highlighted the Senior Executive Service background of [[john-godfrey|John Godfrey]], the SES official Joe Biden dispatched as ambassador to [[sudan|Sudan]] in 2022, as part of an argument that the [[state-department|State Department]] bureaucracy pursued a destabilization campaign to block a [[russian-naval-base-in-sudan|Russian naval base]] at Port Sudan.[{N}]')

a('rapid-support-forces', 'Trump pledge on Sudan (November 2025)',
 'Since the outbreak of war in April 2023, fighting between the [[sudanese-armed-forces|Sudanese army]] and the paramilitary Rapid Support Forces has killed tens of thousands of people and displaced nearly 12 million.[{N}] In November 2025 President [[donald-trump|Donald Trump]] said he would begin working on ending the conflict at the request of Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]], condemning the "tremendous atrocities" of the civil war and pledging to coordinate with Saudi Arabia, the United Arab Emirates and Egypt.[{N}]')

a('sudanese-armed-forces', 'Civil war toll and US involvement pledge (2025)',
 'The war between the Sudanese army and the paramilitary [[rapid-support-forces|Rapid Support Forces]], which began in April 2023, had killed tens of thousands of people and displaced nearly 12 million by November 2025, when President [[donald-trump|Donald Trump]] pledged to start "working" on ending the conflict at the request of Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]].[{N}]')

a('4th-psychological-operations-group', '"Ghosts in the Machine" recruiting video',
 'In 2022 the 4th Psychological Operations Group — self-described as the "Masters of Influence" and practitioners of information warfare — released a highly controversial recruiting video titled "[[ghosts-in-the-machine|Ghosts in the Machine]]" that instantly went viral.[{N}] Crafted to look like a psychological thriller with unsettling imagery and references to real-life uprisings, and described as designed to target psychological vulnerabilities and create confusion in adversary organizations, the clip asked: "Who\'s pulling the strings?"[{N}] Coverage characterized it as a call to join an elite, secretive team functioning as a puppeteer over hot-button national security threats such as the Chinese and Russian governments, confirming that "the war of tomorrow is fought entirely within the human mind."[{N}] Badlands contributor [[gmoney|GMONEY]] noted a Pepe image appearing on the "KOKO the Clown" figure at the 57-second mark of the 1:17 clip and riffed on its tagline "Words are our weapon."[{N}]')

a('zohran-mamdani', 'Oval Office meeting with Trump (November 2025)',
 'President [[donald-trump|Donald Trump]] agreed to meet Mayor-elect Mamdani for the first time at the [[white-house|White House]] on Friday, November 21, 2025, an unexpected sit-down with the Democratic socialist whose election he had opposed.[{N}] Trump announced the meeting on Truth Social, writing: "Communist Mayor of New York City, Zohran \'Kwame\' Mamdani, has asked for a meeting. We have agreed that this meeting will take place at the Oval Office on Friday, November 21st."[{N}] Trump had urged New York voters to back Mamdani\'s opponent, former Governor Andrew Cuomo, and had repeatedly attacked him publicly.[{N}] Mamdani spokesperson Dora Pekec said the two would discuss public safety, economic security and "the affordability agenda that over one million New Yorkers voted for just two weeks ago"; Mamdani said he had reached out to the White House to discuss affordability, a central plank of his campaign.[{N}]\n\n'
 'Badlands contributor [[ashe-in-america|Ashe in America]] warned the meeting could "undermine everything for which we\'ve worked so hard," arguing that "Mammany Hall" needed to serve as a cautionary example for the nation and that legitimizing the Democratic Socialists of America in the Oval Office amounted to "unity with communists," which she called treason.[{N}]')

a('zaporozhye-nuclear-power-plant', 'Ukrainian embezzlement allegations (2025)',
 'Ukrainian lawmaker Vladimir Ariev claimed in November 2025 that officials in Kiev embezzled millions from contracts filed for the Russia-controlled plant, Europe\'s largest, which has been under Russian control since March 2022.[{N}] Kiev has rejected Russia\'s authority over the site as an "occupation," while Moscow has publicly stated that the plant was incorporated into Russia\'s nuclear sector and that transferring control back to Ukraine is not possible.[{N}] Ariev said more than 200 million hryvnia ($4.7 million) in goods and services were formally registered in the plant\'s name months after it came under Russian control, even though Kiev had no way to deliver anything to the site, and that [[energoatom|Energoatom]] continued filing procurement paperwork through most of 2022 — including 210 million hryvnia for food and canteen supplies between March 15 and August 25, 2022.[{N}]')

a('german-galushchenko', 'Energoatom background and 2025 dismissal',
 'Badlands commentary in November 2025 noted that Galushchenko, dismissed as Ukraine\'s justice minister the previous week after being implicated in a major graft probe described as a "$100 million kickback scheme," had been Vice President of [[energoatom|Energoatom]] before joining the government in 2021.[{N}] The scandal coincided with claims by lawmaker Vladimir Ariev that Ukrainian officials embezzled millions through procurement filed in the name of the Russia-held [[zaporozhye-nuclear-power-plant|Zaporozhye Nuclear Power Plant]].[{N}] There were also calls for President [[volodymyr-zelensky|Volodymyr Zelensky]] to dismiss chief of staff [[andriy-yermak|Andrey Yermak]] over alleged ties to the same affair.[{N}]')

a('andriy-yermak', 'Calls for dismissal amid the Energoatom scandal (2025)',
 'In November 2025 there were calls for President [[volodymyr-zelensky|Volodymyr Zelensky]] to fire his chief of staff, Yermak, who was alleged to be tied to the graft scandal that had already claimed Justice Minister [[german-galushchenko|German Galushchenko]] — a "$100 million kickback scheme" linked to [[energoatom|Energoatom]] and procurement filed for the Russia-held [[zaporozhye-nuclear-power-plant|Zaporozhye Nuclear Power Plant]].[{N}]')

a('volodymyr-zelensky', 'Energoatom graft scandal and the Vindman call demand (November 2025)',
 'In November 2025 Zelensky faced calls to dismiss his chief of staff [[andriy-yermak|Andrey Yermak]] over alleged ties to a "$100 million kickback scheme" that had already led to the dismissal of Justice Minister [[german-galushchenko|German Galushchenko]], a former Vice President of [[energoatom|Energoatom]].[{N}] Separately, Rep. [[eugene-vindman|Eugene Vindman]] invoked his 2019 call with President [[donald-trump|Donald Trump]] — the call that resulted in Trump\'s first impeachment — while demanding release of the transcript of a Trump call with Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]].[{N}]')

a('alexander-vindman', 'Badlands commentary on the Vindman brothers (November 2025)',
 'In November 2025 Badlands contributor [[ashe-in-america|Ashe in America]] wrote that presidential restraint had left "the Vindman brothers emboldened after participating in insurrection / seditious conspiracy / treason, in my opinion based on the public record," asking why such officials "are still walking around free."[{N}] The remarks followed the demand by Alexander\'s twin brother, Rep. [[eugene-vindman|Eugene Vindman]], that President [[donald-trump|Donald Trump]] release the transcript of a call with Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]] recorded after the killing of [[jamal-khashoggi|Jamal Khashoggi]].[{N}]')

a('george-conway', 'Prospective congressional run (November 2025)',
 'George T. Conway III, the former conservative lawyer and one of President [[donald-trump|Donald Trump]]\'s fiercest critics, moved closer in November 2025 to announcing a run for Congress in one of Manhattan\'s wealthiest and bluest districts, pitching himself to potential donors as a top attorney who does not "have any more effs to give."[{N}] Conway, 62, then living in Bethesda, Maryland, hired Democratic pollster Anna Greenberg for a budding campaign to succeed retiring Representative [[jerrold-nadler|Jerrold Nadler]], and was scouting apartments in the district where he had lived and worked before relocating to Washington in 2017, when his wife at the time, Kellyanne Conway, joined the first Trump administration as a senior White House official.[{N}] The Conways divorced in 2023.[{N}] He outlined his pitch at a private virtual event for paid members of [[democracy-docket|Democracy Docket]], the media outlet founded by Democratic attorney [[marc-elias|Marc Elias]].[{N}]')

a('jerrold-nadler', 'Retirement and succession race (2025)',
 'Nadler\'s retirement from his Manhattan congressional seat opened a succession race in one of the wealthiest and bluest districts in New York; in November 2025 former conservative lawyer and Trump critic [[george-conway|George Conway]] moved closer to announcing a campaign to succeed him, hiring Democratic pollster Anna Greenberg.[{N}]')

a('democracy-docket', 'Venue for the Conway congressional pitch (2025)',
 '[[george-conway|George Conway]] outlined his pitch for a Manhattan congressional run on Tuesday, November 18, 2025 at a private virtual event for paid members of Democracy Docket, the media outlet founded by Democratic attorney [[marc-elias|Marc Elias]].[{N}]')

a('marc-elias', 'Democracy Docket event with George Conway (2025)',
 'In November 2025, [[george-conway|George Conway]] used a private virtual event for paid members of [[democracy-docket|Democracy Docket]] — the media outlet founded by Elias — to pitch potential donors on a run for Congress in Manhattan.[{N}]')

a('kayfabe', 'Musk at the MBS White House dinner (November 2025)',
 'Badlands contributor [[burning-bright|Burning Bright]] cited the November 2025 [[white-house|White House]] dinner for Saudi Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]] as proof for "anyone still doubting that Kayfabe is the premier narrative weapon of choice for Donald Trump," pointing to the optics of [[elon-musk|Elon Musk]] appearing as a guest of honor months after his public feud with the president.[{N}] The reading was that "Trump and Elon signal GROWTH" — "all gas, no breaks to the Golden Age."[{N}]')

a('congress', 'Epstein files vote and Ukraine support criticism (November 2025)',
 'The House and Senate both voted on Tuesday, November 18, 2025 to publicly release the government\'s files on [[jeffrey-epstein|Jeffrey Epstein]], sending the [[epstein-files-transparency-act|Epstein Files Transparency Act]] to President [[donald-trump|Donald Trump]]\'s desk for signature the following day.[{N}] Separately, Badlands commentary on revelations of Ukrainian government corruption asked what the affair says about "the US Congress — both Republican and Democrat — who have ardently supported Ukraine for the past 3+ years."[{N}]')

a('department-of-justice', 'Ordered release of the Epstein files (November 2025)',
 'Legislation signed by President [[donald-trump|Donald Trump]] on November 19, 2025 ordered the Justice Department to release documents from its long-running investigation into sex offender [[jeffrey-epstein|Jeffrey Epstein]].[{N}] Attorney General [[pam-bondi|Pam Bondi]] said the department would release the files within 30 days, as required by the [[epstein-files-transparency-act|Epstein Files Transparency Act]], which covers internal communications and investigative materials relating to Epstein and [[ghislaine-maxwell|Ghislaine Maxwell]] but permits redaction of records that would jeopardize an active federal investigation or ongoing prosecution.[{N}]')

a('epstein-files', 'Statutory release mandate (November 2025)',
 'Congress voted on November 18, 2025 to require public release of the Epstein files, and President [[donald-trump|Donald Trump]] signed the [[epstein-files-transparency-act|Epstein Files Transparency Act]] the next day, ordering the [[department-of-justice|Justice Department]] to produce documents from its long-running investigation within 30 days.[{N}] Attorney General [[pam-bondi|Pam Bondi]] retains authority to redact records in specific instances, including material that "would jeopardize an active federal investigation or ongoing prosecution," a provision that drew immediate scrutiny.[{N}]')

a('saudi-arabia', 'Washington visit and investment forum (November 2025)',
 'Crown Prince [[mohammed-bin-salman|Mohammed bin Salman]]\'s November 2025 visit to Washington produced an Oval Office meeting, a black-tie [[white-house|White House]] dinner attended by leading American tech, media and sports figures, and the [[saudi-us-investment-forum|US-Saudi Investment Forum]] at the Kennedy Center, hosted by the Ministry of Investment of Saudi Arabia under the theme "Leadership for Growth: Strengthening the Saudi-US Economic Partnership."[{N}] President [[donald-trump|Donald Trump]] said $270 billion of Saudi investment had already been negotiated and locked in for the US economy, the first portion of a promised $1 trillion.[{N}] The crown prince also asked Trump to help end the war in [[sudan|Sudan]], and Trump said he would work with Saudi Arabia, the United Arab Emirates and Egypt toward that end.[{N}]')

run(U)
